### ISSUE TITLE
CardMonitor.StatusChanged seems to be triggered only once on "hybrid" Card Readers (contact and contact-less)

### ISSUE THREAD

**Issue by jueren** [danm-de/pcsc-sharp#100]
Hello everybody,

first of all: thank you for the great library! 

I just stumbled upon an unexpected event-handling-behaviour with respect to combined card readers (contact and contact-less in one device, for instance the Cherry TC 1300).

So, whenever i create a CardMonitoring context on such a device like  
`var factory = MonitorFactory.Instance.Create(SCardScope.System);`

and then i register Initialization-Events like
`factory.Initialized += (sender, args) => HandleCardInitialized(sender, args);`

Then the initialzation events are invoked PER card-reader-"instance":
- Cherry Smartcard Terminal TC 13xx 0
- Cherry Smartcard Terminal TC 13xx-CL 0

The Card-Inserted and Card-Removed Events are triggered only once, and correctly from the instance, where the card-event actually originated. 

And in the case, where the Monitoring-Contexts on the device is gone, the the Exception is raised per CardMonitor-Context (i.e. for both reader-instances).

Therefore i was expecting, that on the Status Changed Event, the Events are Invoked for both reader-instances, i.e. triggering a Status Changed Events per reader-instance. Which seems not to be the case. 

Can you please clarify, whehter this is the intented way how this works, or whether this is a bug.

Steps to reprocude:

1. Put a Card-Device to the system, that can read both: contact and contact-less smartcards
2. Create a Card-Monitoring-Context and subscribe for all Events (incl. Event handlers):
`var factory = MonitorFactory.Instance.Create(SCardScope.System);`
`factory.Initialized += (sender, args) => HandleCardInitialized(sender, args);`
`factory.StatusChanged += (sender, args) => HandleCardStatusChanged(sender, args);`
`factory.CardInserted += (sender, args) => HandleCardInserted(sender, args);`
`factory.CardRemoved += (sender, args) => HandleCardRemoved(sender, args);`
`factory.MonitorException += (sender, args) => HandleCardMonitorException(sender, args);`
3. Pull the Card-Device out from the System and you can see, that the StatusChanged-Handler is only invoked once. Whereas, the MonitorExeption-Handler was called twice (per Reader-Instance)

Thank you so much for your investigation!

Cheers

**Comment by danm-de** [comment]
Hi,

I've just debugged your described problem using a CardMan 5321. The interesting part starts here:
https://github.com/danm-de/pcsc-sharp/blob/master/src/PCSC/Monitoring/SCardMonitor.cs#L428

It is a blocking P/Invoke API call - [SCardGetStatusChange](https://docs.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetstatuschangew), waiting for state changes. The method will return after disconnecting the reader hardware. Both reader structures [SCARD_READERSTATE](https://docs.microsoft.com/de-de/windows/win32/api/winscard/ns-winscard-scard_readerstatea) are received - but only ONE has the new status 'unavailable'. That's why we see only ONE StatusChangeEvent. 

The next call to `SCardGetStatusChange` returns with an error. It seems that Windows closes the PCSC context a bit too early.

**Comment by jueren** [comment]
Hi,

thank you so much for your detailed answer!

I guess, i have to take care about this on the application level then. For instance build an device inventory and per device a list of possible card-reader-instances (for contact and contact-less).
and in case the status of one of the instances is SCRState.Unavailable i have to "inactivate" the whole device (i.e. both of the card-reader instances).

should i do the same thing, when the card-reader-status-changed event returns SCRState.Ignore or  SCRState.Unknown respectively in the NewState-property?

Also any suggestions for a different approach to handle this are very welcome!

Cheers

**Comment by danm-de** [comment]
The device inventory could work.

Step 1: monitor device changes (see [example](https://github.com/danm-de/pcsc-sharp/blob/master/Examples/MonitorDeviceEvents/Program.cs)) 
Step 2: start one monitor per device

Make sure that you detach/unsubscribe all event handlers (from step 2) if a device disappears.

**Comment by danm-de** [comment]
Closing.
