### ISSUE TITLE
Wrong cast to enum

### ISSUE THREAD

**Issue by EmptySamurai** [danm-de/pcsc-sharp#11]
Hi, there is an error in SCardHelper class in methods where you cast objects to enum members. If value of the object is not present in enum it won't throw exception. Instead the value will be succefully casted but it won't be equal to any other member of enum.

**Comment by danm-de** [comment]
Hi,

yes you're totally right. It will never throw an exception. I really don't know why I put the FlagsAttribute on top of SCardError ... 

What would you do in this case? I am not sure whether it is a good idea to "swallow" the real error code - makes it harder to debug for anyone else.

Greetings,
Daniel

**Comment by danm-de** [comment]
I was thinking about changing the return type for several methods to something like this: 

```C#
abstract class ApiResult<T> {
  public bool Success { get; }
  public T Value { get; }
}
```

One could use extension methods and try to "convert" the value into SCardError.

As a drawback the library will become "incompatible" to previous releases :-(

**Comment by danm-de** [comment]
@EmptySamurai Any ideas?

**Comment by danm-de** [comment]
I'll remove the try-catch blocks in version 3.3.0.0
