### ISSUE TITLE
Is it possible to get the id of reader (win)?

### ISSUE THREAD

**Issue by vnmone** [danm-de/pcsc-sharp#13]
Hi!
At first, thanks for this great library!
Can you tell me, is it possible to get the reader id?

I have 4 readers and cant bind them to reders names(

**Comment by danm-de** [comment]
According to
https://technet.microsoft.com/en-US/library/ff404292%28v=ws.10%29.aspx
the reader name is constructed as follows:
* Vendor name
* Interface device type
* Device unit

[..] _The smart card reader device name is constructed in the form &lt;VendorName&gt;&lt;Type&gt;&lt;DeviceUnit&gt;._ [..]

If you have 4 smard card readers (all coming from the same vendor), it should be possible to distinguish them from their _device unit_ number. ```SCardContext.GetReaders()``` will give you exact these names.

For extended information use the ```SCardReader.GetAttrib``` method after ```SCardReader.Connect```, see
https://msdn.microsoft.com/en-us/library/windows/desktop/aa379559%28v=vs.85%29.aspx

Actually, it is possible that the reader name has some weird characters in it - the related stuff is located here:
/Interop/Windows/WinSCardAPI.cs (Line 77) and
/SCardHelper.cs (Line 88)
in case you want to debug it.

Regards,
Daniel

**Comment by vnmone** [comment]
Hi, thank you very much for your reply!

The problem is that I have 4 card readers and need to sort them in manually. And after each restart of a PC, they acquire different "Device Unit".

If I try to get information about a reader by GetAttrib c AttribId = SCardAttribute.VendorInterfaceDeviceTypeSerialNumber I get the error 50.

SCardAttribute.ChannelId returns 00 00 20 00, that is also not provide any information on the readers identification

**Comment by danm-de** [comment]
The available reader attributes depend on manufacturer, device, ..

There are plenty of ways to identify (and distinguish) devices on Windows. SetupAPI and WMI are the most promising ones.

Here is a simple example, that uses WMI to enumerate all smart card readers of your system: 
 ```c#
using System;
using System.Management;

namespace WmiSmartCardTest
{
    class Program
    {
        static void Main() {
            const string SEARCH_SCOPE = @"\root\cimv2";
            const string SMART_CARD_READER_CLASS = "{50DD5230-BA8A-11D1-BF5D-0000F805F530}";

            var statement = string.Format(@"SELECT * FROM Win32_PnPEntity WHERE ClassGuid = '{0}'", 
                SMART_CARD_READER_CLASS);
            var readers = new ManagementObjectSearcher(SEARCH_SCOPE, statement)
                .Get();

            foreach (var reader in readers) {
                Console.WriteLine(new String('=', 79));
                foreach (var property in reader.Properties) {
                    Console.WriteLine("[{0}] ({1}) = {2}",
                        property.Name,
                        property.Type,
                        property.Value);
                }
            }
        }
    }
}
 ```

BTW: you can use WMI events to subscribe for device change notifications as well.

**Comment by vnmone** [comment]
Danke schön, Daniel!
I will try to use WMI, when get back readers.

**Comment by vnmone** [comment]
I stuck again.
I get deviceId, from WMI, and it looks like unique field. 
But how bind data from WMI and device unit from PCSC?

**Comment by danm-de** [comment]
Isn't there a "name" property or something? I haven't got two identical readers .. so I cannot not test it.

Just used google and found this: 

http://stackoverflow.com/questions/10813041/how-are-pcsc-smart-card-reader-friendly-names-constructed

Maybe this can help you?

**Comment by danm-de** [comment]
Cannot fix

**Comment by kmetic** [comment]
Just for your information, I have two readers of the same model and was curious what happens.

PCSC naming:
```
Identiv uTrust 3700 F CL Reader 0
Identiv uTrust 3700 F CL Reader 1
```

WMI data:
```
===============================================================================
['Availability'] ('UInt16') = ''
['Caption'] ('String') = 'uTrust 3700 F CL Reader'
['ClassGuid'] ('String') = '{50dd5230-ba8a-11d1-bf5d-0000f805f530}'
['CompatibleID'] ('String') = 'System.String[]'
['ConfigManagerErrorCode'] ('UInt32') = '0'
['ConfigManagerUserConfig'] ('Boolean') = 'False'
['CreationClassName'] ('String') = 'Win32_PnPEntity'
['Description'] ('String') = 'uTrust 3700 F CL Reader'
['DeviceID'] ('String') = 'USB\VID_04E6&PID_5790\55021722283075'
['ErrorCleared'] ('Boolean') = ''
['ErrorDescription'] ('String') = ''
['HardwareID'] ('String') = 'System.String[]'
['InstallDate'] ('DateTime') = ''
['LastErrorCode'] ('UInt32') = ''
['Manufacturer'] ('String') = 'Identiv'
['Name'] ('String') = 'uTrust 3700 F CL Reader'
['PNPDeviceID'] ('String') = 'USB\VID_04E6&PID_5790\55021722283075'
['PowerManagementCapabilities'] ('UInt16') = ''
['PowerManagementSupported'] ('Boolean') = ''
['Service'] ('String') = 'CLOUDx64'
['Status'] ('String') = 'OK'
['StatusInfo'] ('UInt16') = ''
['SystemCreationClassName'] ('String') = 'Win32_ComputerSystem'
['SystemName'] ('String') = '...'
===============================================================================
['Availability'] ('UInt16') = ''
['Caption'] ('String') = 'uTrust 3700 F CL Reader'
['ClassGuid'] ('String') = '{50dd5230-ba8a-11d1-bf5d-0000f805f530}'
['CompatibleID'] ('String') = 'System.String[]'
['ConfigManagerErrorCode'] ('UInt32') = '0'
['ConfigManagerUserConfig'] ('Boolean') = 'False'
['CreationClassName'] ('String') = 'Win32_PnPEntity'
['Description'] ('String') = 'uTrust 3700 F CL Reader'
['DeviceID'] ('String') = 'USB\VID_04E6&PID_5790\55021722283081'
['ErrorCleared'] ('Boolean') = ''
['ErrorDescription'] ('String') = ''
['HardwareID'] ('String') = 'System.String[]'
['InstallDate'] ('DateTime') = ''
['LastErrorCode'] ('UInt32') = ''
['Manufacturer'] ('String') = 'Identiv'
['Name'] ('String') = 'uTrust 3700 F CL Reader'
['PNPDeviceID'] ('String') = 'USB\VID_04E6&PID_5790\55021722283081'
['PowerManagementCapabilities'] ('UInt16') = ''
['PowerManagementSupported'] ('Boolean') = ''
['Service'] ('String') = 'CLOUDx64'
['Status'] ('String') = 'OK'
['StatusInfo'] ('UInt16') = ''
['SystemCreationClassName'] ('String') = 'Win32_ComputerSystem'
['SystemName'] ('String') = '...'
```

The naming in WMI data doesn't contain the enumeration, both readers have the same name. I suppose the PCSC reader `Identiv uTrust 3700 F CL Reader 0` is the first one from the WMI data with the device id `USB\VID_04E6&PID_5790\55021722283075` and PCSC reader `Identiv uTrust 3700 F CL Reader 1` the second one with device id `USB\VID_04E6&PID_5790\55021722283081`. 

But! This is an example with two different readers:
PCSC naming:
```
Elatec SmartCard Reader 0 Slot 0
Identiv uTrust 3700 F CL Reader 0
```
WMI data:
```
===============================================================================
['Availability'] ('UInt16') = ''
['Caption'] ('String') = 'uTrust 3700 F CL Reader'
['ClassGuid'] ('String') = '{50dd5230-ba8a-11d1-bf5d-0000f805f530}'
['CompatibleID'] ('String') = 'System.String[]'
['ConfigManagerErrorCode'] ('UInt32') = '0'
['ConfigManagerUserConfig'] ('Boolean') = 'False'
['CreationClassName'] ('String') = 'Win32_PnPEntity'
['Description'] ('String') = 'uTrust 3700 F CL Reader'
['DeviceID'] ('String') = 'USB\VID_04E6&PID_5790\55021722283081'
['ErrorCleared'] ('Boolean') = ''
['ErrorDescription'] ('String') = ''
['HardwareID'] ('String') = 'System.String[]'
['InstallDate'] ('DateTime') = ''
['LastErrorCode'] ('UInt32') = ''
['Manufacturer'] ('String') = 'Identiv'
['Name'] ('String') = 'uTrust 3700 F CL Reader'
['PNPDeviceID'] ('String') = 'USB\VID_04E6&PID_5790\55021722283081'
['PowerManagementCapabilities'] ('UInt16') = ''
['PowerManagementSupported'] ('Boolean') = ''
['Service'] ('String') = 'CLOUDx64'
['Status'] ('String') = 'OK'
['StatusInfo'] ('UInt16') = ''
['SystemCreationClassName'] ('String') = 'Win32_ComputerSystem'
['SystemName'] ('String') = '...'
===============================================================================
['Availability'] ('UInt16') = ''
['Caption'] ('String') = 'SmartCard Slot'
['ClassGuid'] ('String') = '{50dd5230-ba8a-11d1-bf5d-0000f805f530}'
['CompatibleID'] ('String') = 'System.String[]'
['ConfigManagerErrorCode'] ('UInt32') = '0'
['ConfigManagerUserConfig'] ('Boolean') = 'False'
['CreationClassName'] ('String') = 'Win32_PnPEntity'
['Description'] ('String') = 'SmartCard Slot'
['DeviceID'] ('String') = '{50DD5230-BA8A-11D1-BF5D-0000F805F530}\SMARTCARD\7&32CE8FAD&0&00'
['ErrorCleared'] ('Boolean') = ''
['ErrorDescription'] ('String') = ''
['HardwareID'] ('String') = 'System.String[]'
['InstallDate'] ('DateTime') = ''
['LastErrorCode'] ('UInt32') = ''
['Manufacturer'] ('String') = 'Elatec'
['Name'] ('String') = 'SmartCard Slot'
['PNPDeviceID'] ('String') = '{50DD5230-BA8A-11D1-BF5D-0000F805F530}\SMARTCARD\7&32CE8FAD&0&00'
['PowerManagementCapabilities'] ('UInt16') = ''
['PowerManagementSupported'] ('Boolean') = ''
['Service'] ('String') = 'twn4ccidslot'
['Status'] ('String') = 'OK'
['StatusInfo'] ('UInt16') = ''
['SystemCreationClassName'] ('String') = 'Win32_ComputerSystem'
['SystemName'] ('String') = '...'
```

You can see the enumeration is different - eTrust reader is first in PCSC protokol, but second in WMI data. I cannot use this for finding the correct DeviceId for the PCSC reader name, hope somebody smarter can :)

**Comment by danm-de** [comment]
If you want to distinguish two devices (of same vendor/product) you need something unique. A serial number for example.

Maybe your reader supports the SCARD_ATTR_VENDOR_IFD_SERIAL_NO attribute.
https://pcsclite.apdu.fr/api/reader_8h.html#ae1143cec3f4ee0f37dee6cdaf8942e8b

See SCardReader.GetAttrib
