### ISSUE TITLE
SCardContext.cs:  208 throws unhandled exception, Message=Cannot find a smart card reader.

### ISSUE THREAD

**Issue by anzun** [danm-de/pcsc-sharp#15]
Hi, 
thank you very much for your work!

I have a litte problem and I cannot catch the exception thrown with this code, if there is no SCard attached to the computer:

(Visual Studio 2010, x86)

I have tried to catch it with this try/catch block..
Can you give me any hints?

```c#
public Signer() {
            try
            {
                SCardContext context = new SCardContext();
                context.Establish(SCardScope.System);

                // Enumerate readers
                string[] readers = context.GetReaders();

                if (readers == null || readers.Length == 0)
                {
                    Console.WriteLine("CardReaderService", "There are currently no readers installed.");
                    return;
                }
                for (int i = 0; i < readers.Length; i++)
                {
                    var foo = context.GetReaderStatus(readers[i]).CurrentState;
                    if (readers[i].ToUpper().Contains("CHERRY") || readers[i].ToUpper().Contains("OMNIKEY"))
                    {
                        // auskommentiert ist nun Form1 AddReadersToComboBoxReaders ausgelesen
                        // Console.WriteLine("reader name: " + readers[i]);

                        // Create a reader object using the existing context
                        Reader = new SCardReader(context);
                        // Connect to the card and select protocol
                        Reader.Connect(readers[i], SCardShareMode.Shared, SCardProtocol.Any);
                        break;
                    }
                }

                Pci = SCardPCI.GetPci(Reader.ActiveProtocol);
            }
            catch (PCSCException ex)
            {
                Console.WriteLine("Error: "
    + ex.Message
    + " (" + ex.SCardError.ToString() + ")");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: "
    + ex.Message
    + " (" + ex.ToString() + ")");
            }
		}
```

**Comment by danm-de** [comment]
Hi, 

Please post the full stack trace + exception message (+ line numbers).

I am not sure whether I've understand what your code tries to achieve (what's "Reader" and "Pci" - maybe class properties?).

```c#
public void Signer()	{
			var context = new SCardContext();
			context.Establish(SCardScope.System);

			var firstReader = context
				.GetReaders()
				.Select(name => name.ToUpper())
				.FirstOrDefault(name => name.Contains("CHERRY") || name.Contains("OMNIKEY"));

			if (firstReader == null)
			{
				context.Dispose();
				Console.WriteLine("CardReaderService: {0}", "There are currently no readers installed.");
				// TODO: Reset "Reader" and "Pci" properties / fields
				return;
			}

			// TODO: Set Reader property here
			var reader = new SCardReader(context);
			if (reader.Connect(firstReader, SCardShareMode.Shared, SCardProtocol.Any) != SCardError.Success)
			{
				context.Dispose();
				Console.WriteLine("CardReaderService: Error while connecting to reader {0}.", reader);
				// TODO: Reset "Reader" and "Pci" properties / fields
				return;
			}

			// TODO: Set Pci property here
			var pci = SCardPCI.GetPci(reader.ActiveProtocol);
		}
```

**Comment by danm-de** [comment]
SCardContext.GetReaders(..) can throw:
- InvalidContextException (on invalid / destroyed SCardContext)
- PCSCException (.. unknown error - cannot reproduce this)

**Comment by anzun** [comment]
The full trace:

PCSC.PCSCException wurde nicht behandelt.
  Message=Cannot find a smart card reader.
  Source=pcsc-sharp
  StackTrace:
       bei PCSC.SCardContext.GetReaders(String[] groups) in d:\danm\Dokumente\GitHub\pcsc-sharp\pcsc-sharp\SCardContext.cs:Zeile 208.
       bei PCSC.SCardContext.GetReaders() in d:\danm\Dokumente\GitHub\pcsc-sharp\pcsc-sharp\SCardContext.cs:Zeile 232.
       bei WindowsFormsPCSCSignaturSample.Form1.AddReadersToComboBoxReaders() in C:\Users\an\documents\visual studio 2010\Projects\WindowsFormsPCSCSignaturSample\WindowsFormsPCSCSignaturSample\Form1.cs:Zeile 408.
       bei WindowsFormsPCSCSignaturSample.Form1..ctor() in C:\Users\an\documents\visual studio 2010\Projects\WindowsFormsPCSCSignaturSample\WindowsFormsPCSCSignaturSample\Form1.cs:Zeile 63.
       bei WindowsFormsPCSCSignaturSample.Program.Main() in c:\users\an\documents\visual studio 2010\Projects\WindowsFormsPCSCSignaturSample\WindowsFormsPCSCSignaturSample\Program.cs:Zeile 18.
       bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       bei System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       bei System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by anzun** [comment]
Debugging the code I found in WinSCardAPI.cs in Line 92
        public SCardError ListReaders(IntPtr hContext, string[] groups, out string[] readers) {
            var dwReaders = 0;

            // initialize groups array
            byte[] mszGroups = null;
            if (groups != null)
                mszGroups = SCardHelper.ConvertToByteArray(groups, _textEncoding);

            // determine the needed buffer size
            var rc = SCardHelper.ToSCardError(
                SCardListReaders(hContext,
                    mszGroups,
                    null,
                    ref dwReaders));

            if (rc != SCardError.Success) {
                readers = null;
                return rc;
            }

the SCardError to be -2146435026 (Hex: 0x8010002e)


In SCardContext.cs the exception is thrown
                    throw new PCSCException(rc, SCardHelper.StringifyError(rc));

in SCardHelper.cs 
in line 42 
                return (attributes.Length > 0)
                    ? attributes[0].Description
                    : attr.ToString();
I can see that attributes[0].Description = "Cannot find a smart card reader."
