### ISSUE TITLE
Authentication Failed While Reading the Data

### ISSUE THREAD

**Issue by GautamAgrawal** [danm-de/pcsc-sharp#16]
HI ! I am getting the authentication exception while reading M1fare Çard 1K. Please suggest the changes I need to make

**Comment by danm-de** [comment]
Full stack trace?
Did you use my RFID sample? If yes, did you double check the key?

**Comment by GautamAgrawal** [comment]
I am using Mifare1kTest sample provided in your demo. When I ran the application I am getting "Authentication Failed Issue". I am not sure about the key where I need to change. Please help me.

**Comment by GautamAgrawal** [comment]
Do you want me to send the dump file for this ?

**Comment by danm-de** [comment]
Please make sure that you have read and understand the Mifare 1K specification. pcsc-sharp is NOT a ready-to-use library for accessing RFID cards / chips.

The "key part" is at line 36 (comment "// key"). You MUST provide a valid key for YOUR card + slot. 

Greetings,
Daniel
