### ISSUE TITLE
Mifare1kTest Example not working

### ISSUE THREAD

**Issue by Hundling** [danm-de/pcsc-sharp#17]
The function 
```
public bool LoadKey(KeyStructure keyStructure, int keyNumber, byte[] key) {
```
doesn't succeed.
Debugging Message: 
> Load Authentication Keys: FF-82-00-00-06-FF-FF-FF-FF-FF-FF
> SW1 SW2 = 69 88

The ISO specification says, that 6988 stands for " SM data objects incorrect "
![Cardwerk ISO Specification Table 17](www.cardwerk.com/smartcards/smartcard_standard_ISO7816-4_5_basic_organizations.aspx)

Error in command or understanding?

**Comment by danm-de** [comment]
Hi,
have a look here:
http://stackoverflow.com/questions/31271372/scl011-contactless-card-reader-and-mifare-1kclassic-authentification

**Comment by danm-de** [comment]
No answer, closing ticket.
