### ISSUE TITLE
Bug in CommandApdu.ToArray()   for IsoCase.Case4Extended

### ISSUE THREAD

**Issue by andrew7webb** [danm-de/pcsc-sharp#19]
The code currently is:
Array.Copy(_data, 0, apdu, pos, **255**);  
pos += _lc;

255 can't be right as lc is not always 255.

I suggest    Array.Copy(_data, 0, apdu, pos, **Data.Length**);  

Testing code:

I tried my fix with
                    var apduSelPiv = new CommandApdu(IsoCase.Case4Short, isoReader.ActiveProtocol)
                    {
                        CLA = 0x00, // Class
                        Instruction = InstructionCode.SelectFile,
                        P1 = 0x04,  // Parameter 1
                        P2 = 0x0C,  // Parameter 2   Skip the FCI
                        Le = 0x00   // Expected length of the returned data
                    };
                    apduSelPiv.Data = new byte[] { 0xa0, 0x00, 0x00, 0x03, 0x08, 0x00, 0x00, 0x10, 0x00, 0x01, 0x00 };
                    var responseSelPiv = isoReader.Transmit(apduSelPiv);

                    Console.WriteLine("Send APDU with \"SELECT PIV\" command: {0}", BitConverter.ToString(apduSelPiv.ToArray()));
                    Console.WriteLine("SW1 SW2 = {0:X2} {1:X2} ", responseSelPiv.SW1, responseSelPiv.SW2);
                    Console.WriteLine();
  

                    // Get Data CHUID using extended length 
                    // 00 cb 3f ff  00 00 05   5c 03 5f c1 02   00 00
                    //
                    var apduGetDataChuid = new CommandApdu(IsoCase.Case4Extended, isoReader.ActiveProtocol)
                    {
                        CLA = 0x00, // Class
                        Instruction = InstructionCode.GetDataPivB,
                        P1 = 0x3F,  // Parameter 1
                        P2 = 0xFF,  // Parameter 2   Skip the FCI
                        Le = 0x00   // Expected length of the returned data
                    };
                    apduGetDataChuid.Data = new byte[] { 0x5C, 0x03, 0x5F, 0xC1, 0x02 };
                    var responseGetChuid = isoReader.Transmit(apduGetDataChuid);
                    Console.WriteLine("Get Data CHUID {0} = SW1 SW2 = {1:X2} {2:X2}", BitConverter.ToString(apduGetDataChuid.ToArray()), responseGetChuid.SW1, responseGetChuid.SW2 );
                    Console.WriteLine("Data returned: {0}", BitConverter.ToString(responseGetChuid.GetData()));
                    Console.WriteLine();

and was able to read a PIV CHUID with extended length,

**Comment by danm-de** [comment]
Ouch!

**Comment by danm-de** [comment]
Thanks for reporting!

@andrew7webb Can you help with this issue?
-> https://github.com/danm-de/pcsc-sharp/pull/9
