### ISSUE TITLE
Error Code 122

### ISSUE THREAD

**Issue by anzun** [danm-de/pcsc-sharp#20]
Hi, first of all, I would like to thank you for this wonderful work!

Here is a problem, when I send the following command several times within a short period of time:

```
using (var context = new SCardContext())
                    {
                        context.Establish(SCardScope.System);
                        using (IsoReader isoReader = new IsoReader(context, strReaderName, SCardShareMode.Shared, SCardProtocol.Any, false))
                        {
                            SmartCard smartCard = new SmartCard(isoReader);
                            **strSerialnumberCardReader = smartCard.getCertificateSerialDecimal();**
.....
```

```
        public string getCertificateSerialDecimal()
        {
            System.Numerics.BigInteger bigCertSerial = **getCertificateSerialBig**(isoReader);
            return bigCertSerial.ToString();
        }
```

```
        private System.Numerics.BigInteger getCertificateSerialBig(IsoReader isoReader)
        {
            byte[] ba = **getBufferCert**(isoReader, EF_CERT, true);
            System.Numerics.BigInteger bigCertSerial = 0;
            int intCertSerialIndex = 14;

            if (ba.Length > 0)
            {
                byte length = ba[intCertSerialIndex];
                byte[] byteCertSerial = new byte[length];
                Array.Copy(ba, intCertSerialIndex + 1, byteCertSerial, 0, length);
                if (BitConverter.IsLittleEndian) Array.Reverse(byteCertSerial);
                bigCertSerial = new System.Numerics.BigInteger(byteCertSerial);

            }
            return bigCertSerial;
        }
```

 ```
private byte[] getBufferCert(IsoReader isoReader, byte[] certToRead, bool onlyFirst)
        {
            Response responseDF = sendSelectGlobaltrustAID(SELECT_DF); // response 144 0 = 0x9000 OK
            Response responseCRT = sendSelectGlobaltrustFID(certToRead);
            byte[] result = null;
            if ((responseDF.StatusWord == 0x9000) && responseCRT.StatusWord == 0x9000)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    int offset = 0;
                    while (true)
                    {
                        CommandApdu apdu = readDataAPDU(isoReader, (byte)(offset >> 8), (byte)offset); // 00 B0 00 00 > erste 258 (davon 256 data) Bytes lesen
                        **Response response = isoReader.Transmit(apdu);**
                        if (response.StatusWord != 0x9000)
                        {
                            break;
                        }
                        byte[] responseData = response.GetData();
                        ms.Write(responseData, 0, responseData.Length);
                        if (onlyFirst)
                        {
                            break;
                        }
                        offset += 256; // 00 B0 01 00 > 00 B0 02 00 etc nächste 256 data Bytes lesen
                    }
                    result = ms.ToArray();
                }
            }
            return result;
        }
```

```
        private static CommandApdu readDataAPDU(IsoReader isoReader, byte p1, byte p2)
        {
            CommandApdu toReturn = new CommandApdu(IsoCase.Case2Short, isoReader.ActiveProtocol)
            { //     Lc is valued to 0. Le is valued from 1 to 256. No data byte is present.
                CLA = 0x00,
                INS = 0xB0,
                P1 = p1,
                P2 = p2,
                Le = 0
            };
            return toReturn;
        }

```

Stack Trace
bei PCSC.SCardErrorExtensionMethods.Throw(SCardError sc) in D:\\danm\\Dokumente\\GitHub\\pcsc-sharp\\pcsc-sharp\\ExtensionMethods\\SCardErrorExtensionMethods.cs:Zeile 52.
   bei PCSC.Iso7816.IsoReader.SimpleTransmit(Byte[] commandApdu, Int32 commandApduLength, IsoCase isoCase, SCardProtocol protocol, SCardPCI receivePci, Byte[] receiveBuffer, Int32 receiveBufferLength) in D:\\danm\\Dokumente\\GitHub\\pcsc-sharp\\pcsc-sharp\\Iso7816\\IsoReader.cs:Zeile 165.
   bei PCSC.Iso7816.IsoReader.Transmit(CommandApdu commandApdu) in D:\\danm\\Dokumente\\GitHub\\pcsc-sharp\\pcsc-sharp\\Iso7816\\IsoReader.cs:Zeile 194.
   bei GxAPI.SmartCard.getBufferCert(IsoReader isoReader, Byte[] certToRead, Boolean onlyFirst)
   bei GxAPI.SmartCard.getCertificateSerialBig(IsoReader isoReader)
   bei GxAPI.SmartCard.getCertificateSerialDecimal()

I was going through the debugger and noted this:

IsoReader.cs
Line 194 ff
  var responseApdu = SimpleTransmit(
                sendBuffer,
                sendBuffer.Length,
                commandApdu.Case, // ISO case used by the Command APDU
                commandApdu.Protocol, // Protocol used by the Command APDU
                receivePci,
                ref receiveBuffer,
                ref receiveBufferLength);
Exception

Line 137 ff
                sc = Reader.Transmit(
                    SCardPCI.GetPci(Reader.ActiveProtocol),
                    commandApdu,
                    commandApduLength,
                    receivePci,
                    receiveBuffer,
                    ref receiveBufferLength);

ScardReader.cs 
Line 924 ThrowOnInvalidCardHandle();
        public SCardError Transmit(IntPtr sendPci, byte[] sendBuffer, int sendBufferLength, SCardPCI receivePci,
            byte[] receiveBuffer, ref int receiveBufferLength) {
            ThrowOnInvalidCardHandle();

not thrown CardHandle != 0
        private void ThrowOnInvalidCardHandle() {
            if (_cardHandle.Equals(IntPtr.Zero)) {
                throw new InvalidOperationException(
                    "Reader is currently not connected or no card handle has been returned.");
            }
        }
-368377856

Line 931 ff
            return Platform.Lib.Transmit(
                _cardHandle,
                sendPci,
                sendBuffer,
                sendBufferLength,
                ioRecvPciPtr,
                receiveBuffer,
                ref receiveBufferLength);

WinSCardAPI.cs
Line 271 ff
            var rc = SCardHelper.ToSCardError((SCardTransmit(
                hCard,
                pioSendPci,
                pbSendBuffer,
                sendbuflen,
                pioRecvPci,
                pbRecvBuffer,
                ref recvlen)));

ScardHelper.cs
        internal static SCardError ToSCardError(int result) {
            return (SCardError) result;
        }

result = 122

finally going into SCardErrorExtensionMethods.cs

**Comment by danm-de** [comment]
Hallo,
ehm zuviel Code - da kann ich nur "raten".

Was heißt kurze Zeit? Reden wir hier von Millisekunden oder Sekunden?
Werden die Abfragen sequentiell oder parallel durchgeführt? (Pcsc-sharp ist nicht thread-safe!)
Werden die Lese/Schreib-Buffer/Apdus in anderen Methoden modifiziert und/oder wiederverwendet/recycelt?
Ist sichergestellt das der Kontext nirgends disposed wird?

Fehler 122 kommt aus der winerr.h und lautet ERROR_INSUFFICIENT_BUFFER
https://msdn.microsoft.com/de-de/library/windows/desktop/ms681382(v=vs.85).aspx

Diesen Fehler habe ich nicht abgefangen, da er (eigentlich) auf einen fehlerhaften Eingangsparameter der Windows-API-Methode SCardTransmit hinweist - wird die CommandApdu von einem anderen Thread modifiziert?

**Comment by danm-de** [comment]
Mit dem Kommando stimmt etwas nicht. IsoCase2 erwartet Daten als Antwort aber -> Le=0?
Was passiert, wenn die Expected Length auf Le=255 Bytes gesetzt wird?

**Comment by anzun** [comment]
Danke für den Tipp!

Ich habe nun LE= 255 gesetzt und ja, nun funktioniert jeder Durchlauf des Befehles.
Interessant ist, dass es beim **ersten** Durchlauf auch mit **Le = 0** funktioniert...

Ich habe den Code von http://labs.a-trust.at/developer/downloads/apduExamples_0.3.zip
angepasst übernommen. (Für alle, die auf das gleiche Problem stoßen)

        private static CommandApdu generateResponseAPDU(IsoReader isoReader, byte cla, byte ins, byte p1, byte p2) {
            CommandApdu toReturn = new CommandApdu(IsoCase.Case2Short, isoReader.ActiveProtocol) {
                CLA = cla,
                INS = ins,
                P1 = p1,
                P2 = p2,
                **Le = 0**
            };
            return toReturn;
        }

**Comment by danm-de** [comment]
Ich habe das Error-Handling etwas verbessert:
https://www.nuget.org/packages/PCSC/3.4.0
Mich würde interessieren welche Fehlermeldung bzw. welche Exception jetzt kommt. Ich habe keine entsprechenden Smartcards zur Verfügung.

**Comment by anzun** [comment]
Hallo Daniel, vielen Dank!

Ja, nun ist die Fehlermeldung sehr aussagekräftig.
((PCSC.Iso7816.InvalidApduException)(ex))
{"Unsufficient buffer: check Le size (Le=0)"}

"PCSC.Iso7816.InvalidApduException" wurde aufgefangen.
  Message=Unsufficient buffer: check Le size (Le=0)
  Source=pcsc-sharp
  StackTrace:
       bei PCSC.Iso7816.IsoReader.Transmit(CommandApdu commandApdu) in D:\danm\Dokumente\GitHub\pcsc-sharp\pcsc-sharp\Iso7816\IsoReader.cs:Zeile 201.
       bei GxAPI.SmartCard.getBufferCert(IsoReader isoReader, Byte[] certToRead, Boolean onlyFirst) in ....
  InnerException: PCSC.WinErrorInsufficientBufferException
       Message=The data area passed to a system call is too small.
       Source=pcsc-sharp
       StackTrace:
            bei PCSC.SCardErrorExtensionMethods.Throw(SCardError sc) in D:\danm\Dokumente\GitHub\pcsc-sharp\pcsc-sharp\ExtensionMethods\SCardErrorExtensionMethods.cs:Zeile 52.
            bei PCSC.Iso7816.IsoReader.SimpleTransmit(Byte[] commandApdu, Int32 commandApduLength, IsoCase isoCase, SCardProtocol protocol, SCardPCI receivePci, Byte[]& receiveBuffer, Int32& receiveBufferLength) in D:\danm\Dokumente\GitHub\pcsc-sharp\pcsc-sharp\Iso7816\IsoReader.cs:Zeile 164.
            bei PCSC.Iso7816.IsoReader.Transmit(CommandApdu commandApdu) in D:\danm\Dokumente\GitHub\pcsc-sharp\pcsc-sharp\Iso7816\IsoReader.cs:Zeile 192.
       InnerException: 

Ich habe nun eine Fallbehandlung eingebaut (auch wenn das für mich nicht ganz nachvollziehbar ist, warum es beim Auslesen des gesamten Certificate nur mit Le = 0 funktioniert):

Wenn ich nur den ersten Block aus dem Certificate auslese: Le = 255
Wenn ich das ganze Certificate auslese (mit einer while-Schleife) dann mit  Le = 0

Ohne dieser Fallbehandlung und weiterer Fehlerbehandlung laufe ich bei Le= 0 beim nächsten Auslesen des ersten Block des Certificate in den Folgefehler:
System.Exception._COMPlusExceptionCode
-532462766

{"Error code: 1117"}

"   bei PCSC.SCardErrorExtensionMethods.Throw(SCardError sc) in D:\\danm\\Dokumente\\GitHub\\pcsc-sharp\\pcsc-sharp\\ExtensionMethods\\SCardErrorExtensionMethods.cs:Zeile 54.
   bei PCSC.Iso7816.IsoReader.SimpleTransmit(Byte[] commandApdu, Int32 commandApduLength, IsoCase isoCase, SCardProtocol protocol, SCardPCI receivePci, Byte[]& receiveBuffer, Int32& receiveBufferLength) in D:\\danm\\Dokumente\\GitHub\\pcsc-sharp\\pcsc-sharp\\Iso7816\\IsoReader.cs:Zeile 164.
   bei PCSC.Iso7816.IsoReader.Transmit(CommandApdu commandApdu) in D:\\danm\\Dokumente\\GitHub\\pcsc-sharp\\pcsc-sharp\\Iso7816\\IsoReader.cs:Zeile 192.

**Comment by anzun** [comment]
Interessanterweise komme ich zum selben Fehler, wenn ich zuerst die Certificate-Number auslese, also nur den ersten Block aus dem Certificate auslese: Le = 255 und anschließend innerhalb von wenigen Sekunden versuche das gesamte Certificate auslese (mit einer while-Schleife und mit Le = 0)
Wenn ich mehr als 20 Sekunden zwischen diesen Schritten verstreichen lasse, kann ich das gesamte Certificate auslesen. Hat jemand einen Tipp?

**Comment by danm-de** [comment]
Ich habe einen Test-Branch bugfix/InsufficientBuffer angelegt:
https://github.com/danm-de/pcsc-sharp/tree/bugfix/InsufficientBuffer
Die Methode IsoReader.SimpleTransmit(..) erkennt dort den Sondernfall ERROR_INSUFFICIENT_BUFFER. 

pcsc-sharp lässt sich mit `build.cmd` automatisch kompilieren. Mittels `build.cmd NuGet` kann lokal ein NuGet-Paket erzeugt werden.

Um den Fehler genauer zu analysieren ist es vielleicht von Vorteil das Projekt direkt einzubinden. 

Da ich das Protokoll der Karte nicht kenne, kann ich keine leider applikationsspezifischen Fragen beantworten.

**Comment by anzun** [comment]
Danke. Ich werde das Anfang kommender Woche testen.

**Comment by anzun** [comment]
{"The data area passed to a system call is too small."}

SCardError	
WinErrorInsufficientBuffer	
PCSC.SCardError

bei PCSC.SCardErrorExtensionMethods.Throw(SCardError sc) in D:\\danm\\Dokumente\\GitHub\\pcsc-sharp\\pcsc-sharp\\ExtensionMethods\\SCardErrorExtensionMethods.cs:Zeile 52.
bei PCSC.Iso7816.IsoReader.SimpleTransmit(Byte[] commandApdu, Int32 commandApduLength, IsoCase isoCase, SCardProtocol protocol, SCardPCI receivePci, Byte[]& receiveBuffer, Int32& receiveBufferLength) in D:\\danm\\Dokumente\\GitHub\\pcsc-sharp\\pcsc-sharp\\Iso7816\\IsoReader.cs:Zeile 164.
bei PCSC.Iso7816.IsoReader.Transmit(CommandApdu commandApdu) in D:\\danm\\Dokumente\\GitHub\\pcsc-sharp\\pcsc-sharp\\Iso7816\\IsoReader.cs:Zeile 192."

**Comment by anzun** [comment]
Soll ich noch weitere Tests durchführen? Ist obige Fehlermeldung/Stacktrace hilfreich?

**Comment by danm-de** [comment]
Danke, das ist aber nicht die Version vom Branch "bugfix/InsufficientBuffer" sondern vom "master".

https://github.com/danm-de/pcsc-sharp/blob/bugfix/InsufficientBuffer/pcsc-sharp/Iso7816/IsoReader.cs
Zeile 164 ist dort ein Kommentar.

Da IsoCase2 normalerweise Daten erwartet (also Le != 0) würde ich mich an den Kartenhersteller wenden - muss das Kommando wirklich SO aussehen? Vielleicht ist das Beispielprojekt und/oder die Beispielbibliothek fehlerhaft. Eventuell kann auch jemand mit _mehr_ Erfahrung bzgl. ISO-7816 weiterhelfen.

**Comment by anzun** [comment]
Danke für den Hinweis.

ich denke ich habe nun die korrekte Version eingebunden...

```
"PCSC.WinErrorInsufficientBufferException" wurde aufgefangen.
  Message=The data area passed to a system call is too small.
  Source=pcsc-sharp
  StackTrace:
       bei PCSC.SCardErrorExtensionMethods.Throw(SCardError sc) in d:\danm\Dokumente\GitHub\pcsc-sharp\pcsc-sharp\ExtensionMethods\SCardErrorExtensionMethods.cs:Zeile 52.
       bei PCSC.Iso7816.IsoReader.SimpleTransmit(Byte[] commandApdu, Int32 commandApduLength, IsoCase isoCase, SCardProtocol protocol, SCardPCI receivePci, Byte[] receiveBuffer, Int32 receiveBufferLength) in d:\danm\Dokumente\GitHub\pcsc-sharp\pcsc-sharp\Iso7816\IsoReader.cs:Zeile 158.
       bei PCSC.Iso7816.IsoReader.Transmit(CommandApdu commandApdu) in d:\danm\Dokumente\GitHub\pcsc-sharp\pcsc-sharp\Iso7816\IsoReader.cs:Zeile 188.
  InnerException: 

```

Interessant ist, dass dieser Fehler nur auftritt, wenn ich die Applikation direkt aus VS2010 im Debugger starte, nicht, wenn ich die kompilierte exe starte.

Wie gesagt: der Code ist von http://labs.a-trust.at/developer/downloads/apduExamples_0.3.zip
angepasst übernommen.
Die Karte ist von Globaltrust - einem zweiten Anbieter für RKSV-konforme Signaturkarten (Österreichische Registrierkassensicherheitsverordnung).

Das Codebeispiel von Globaltrust, das mir zur Verfügung steht sendet direkte APDUs an die Karte

```
X509Certificate userCertificate = signer.ReadCertificateFromCard(Signer.APDU_SELECT_USER_CERTEF);
Console.WriteLine("user certificate serial#: " + userCertificate.SerialNumber);

public static readonly byte[] APDU_SELECT_USER_CERTEF =  "00a40804041160c001".ToByteArray();
```

und unterscheidet nicht die beiden Fälle, wo nur die SerialNumber abgefragt wird `onlyFirst=true`
und den Fall wo das gesamte Zertifikat abgefragt wird `onlyFirst=false`, wie es bei A-Trust möglich ist:

Die Lösung mit Le=0 finde ich auch etwas eigenartig und ich bin auch verwundert, das dies funktioniert, außer man sendet im Debugger zu schnell hintereinander getBuffer(isoReader, **true**) und anschließend getBuffer(isoReader, **false**)

```
        private ulong getCertificateSerial(IsoReader isoReader) {
            byte[] ba = getBuffer(isoReader, **true**);
            byte length = ba[14];
            ulong res = 0;
            for (int i = 0; i < length; i++) {
                res = (res << 8) + ba[15 + i];
            }
            return res;
        }

        public X509Certificate getCertificate() {
            X509Certificate cert = new X509Certificate(getBuffer(isoReader, **false**));
            return cert;
        }

        private byte[] getBuffer(IsoReader isoReader, bool onlyFirst) {
            sendSelectFID(DF_SIG);
            sendSelectFID(EF_C_CH_DS);
            byte[] result = null;
            using (MemoryStream ms = new MemoryStream()) {
                int offset = 0;
                while (true) {
                    CommandApdu apdu = generateResponseAPDU(isoReader, 0x00, 0xB0, (byte)(offset >> 8), (byte)offset);
                    Response response = isoReader.Transmit(apdu);
                    if (response.StatusWord != 0x9000) {
                        break;
                    }
                    byte[] responseData = response.GetData();
                    ms.Write(responseData, 0, responseData.Length);
                    if (onlyFirst) {
                        break;
                    }
                    offset += 256;
                }
                result = ms.ToArray();
            }
            return result;
        }

        private static CommandApdu generateResponseAPDU(IsoReader isoReader, byte cla, byte ins, byte p1, byte p2) {
            CommandApdu toReturn = new CommandApdu(IsoCase.Case2Short, isoReader.ActiveProtocol) {
                CLA = cla,
                INS = ins,
                P1 = p1,
                P2 = p2,
                Le = 0
            };
            return toReturn;
        }

```
Wenn jemand einen anderen Lösungsweg hat wäre ich sehr dankbar für den Input.

**Comment by danm-de** [comment]
Vielleicht mal bei StackOverflow oder beim Hersteller nachfragen. Mir scheint das sehr Karten- bzw. Applikationsspezifisch zu sein. Danke für den Hinweis - ich hoffe die Fehlerausgabe in pcsc-sharp so verbessert zu haben, das zukünftig der Anwender schneller die Fehlerursache herausfindet.

**Comment by anzun** [comment]
Danke für den Tipp mit StackOverflow :)
Und danke für die Verbesserung. Ich finde es sehr hilfreich und das wird sicherlich anderen auch so gehen.
