### ISSUE TITLE
Send URl via NDEF possible?

### ISSUE THREAD

**Issue by SunboX** [danm-de/pcsc-sharp#21]
I want to do something like this:
https://github.com/Seeed-Studio/PN532/blob/master/PN532/examples/emulate_tag_ndef/emulate_tag_ndef.ino#L22

I tried your samples and they all are working using my reader. It's one of these: 
http://www.acs.com.hk/en/products/3/acr122u-usb-nfc-reader

Can I use this library to push such a NDEF message? If so, how?

greetings from Germany,
André

**Comment by danm-de** [comment]
Hi André,

Probably yes. You have to build the necessary commands by yourself though. pcsc-sharp is *just* a wrapper to Windows & Linux native PC/SC library not a ready-to-use NFC library.

Springcard's SDK could be helpful, they have a NFStool written in C#

http://www.springcard.com/en/download/sdks
http://files.springcard.com/pub/pcsc-sdk_2-21.zip
