### ISSUE TITLE
Changing authentication key for the first sector of 1K Mifare card

### ISSUE THREAD

**Issue by ithieund** [danm-de/pcsc-sharp#23]
Hi Daniel Mueller,
Can you help me to change the authentication key for the first sector of 1K Mifare card?
They said that we have to write a combination of new Key A, Access Condition Bits, and Key B into the Sector Trail but how can I do that with your lib?
https://www.mifare.net/support/forum/topic/how-change-key-mifare-classic-card/

An example is very helpful.
Thanks in advance.

**Comment by danm-de** [comment]
Hi,

You can find many examples written in C++ and/or VB/C# from card vendors. Once you find out which commands are required, you can use ISCardReader.Transmit to send commands as "raw" binary data or IIsoReader.Transmit using a prepared APDU.

https://www.hidglobal.com/omnikey-contactless-developer-guide
https://github.com/hidglobal/mifare-sample/blob/master/MifareTest.cpp
http://stackoverflow.com/questions/4842087/mifare-change-key-a-and-b

Greetings,
Daniel

**Comment by ithieund** [comment]
@danm-de ,
Thank you very much for your help.
But i'm new to this topic and still don't know how to do.
Can you give me a sample code with your library?

Thank you very much.
