### ISSUE TITLE
High CPU Usage after a few hours of running context

### ISSUE THREAD

**Issue by luetm** [danm-de/pcsc-sharp#27]
Hi!

We use your library in production and seem to be running into an issue with CPU usage after the client doesn't close the application for a while.

After running dotTrace over the application after the client reported a slow down, we had the result shown in the attachment. It was the only thread with high CPU usage!

Can you help out, please?

![image](https://cloud.githubusercontent.com/assets/5311183/14712399/470483aa-07dd-11e6-8037-fcb5b314a551.png)

Thanks for the great lib! :)

**Comment by luetm** [comment]
Our fault. Ignore.

**Comment by danm-de** [comment]
Hi,
Which version do you use?

Daniel
