### ISSUE TITLE
Detect cards already present before Monitor Start()

### ISSUE THREAD

**Issue by Philekunf** [danm-de/pcsc-sharp#30]
Hi Daniel!

First let me thank you for a wonderful library, I was using a poorly implemented library before this one and since I needed to run some heavy modifications to my NfcController class, I opted to switch to this one first. I am also considering forking and submitting a few pull requests here if you find them pertinent.

This issue concerns the SCardMonitor class which does not fire a CardFound Event on load if a card is already present on the reader. I don't recall exactly how the events did it in the previous library I used but this is one of the few features it had over this one.

Basically when my software launches, it cannot read a card that was already on the reader until I remove and reapproach it. That is partly my fault, as it would probably work to connect and transmit to the card but I am using a bool variable on the CardFound and CardRemoved events to prevent even trying.

Is there a way currently to know a card is present at initialization time from either the SCardReader or SCardMonitor?

Here is a sample of my code

```
    public class NfcController: IDisposable
    {
        public NfcController() 
        {
            _context = new SCardContext();
            _context.Establish(SCardScope.System);
            var readerList = _context.GetReaders().ToList();
            if (!readerList.Any()) throw new ApplicationException("Could not initialize NFC reader.");
            _readerName = readerList[DEFAULT_READER];
            _reader = new SCardReader(_context);
            _reader.ApduSent += OnApduSent;
            _reader.ApduReceived += OnApduReceived;

            _monitor = new SCardMonitor(_context, SCardScope.System);
            _monitor.CardInserted += OnCardFound;
            _monitor.CardRemoved += OnCardRemoved;
            _monitor.MonitorException += OnError;
            _monitor.Start(new[] { _readerName });

            //todo: trigger initial cardFound event.
            //Not working
            if (_monitor.GetCurrentState(0) == ScrState.Present) //Current state on load is "Unaware" :(
            {
                //do something!
            }
        }

        //...
        private const int DEFAULT_READER = 0x00;
        private readonly SCardMonitor _monitor;
        private readonly SCardReader _reader;
        private readonly SCardContext _context;
        //...
    }
```

**Comment by danm-de** [comment]
Hi,

Thanks, nice to read!

Did the SCardMonitor.Initialized event not work for you?

If I remember correctly, it should raise soon after calling Start(..) containing the reader's current state (connected/disconnected, ATR,..)?

You could also call SCardContext.GetReaderStatus(..) before starting the monitor.

Best regards,
Daniel
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Philekunf** [comment]
I never noticed the Initalized event while going through the source code!
I will be trying both of these solutions first thing monday morning and report back.

Thank you for the swift reply,
Phil~

**Comment by Philekunf** [comment]
Small correction, after finding that after a while the initial state becomes "Present|Unpowered" and realizing the state is a bit mask.
    

```
private void OnInitialize(object sender, CardStatusEventArgs e)
        {
            if ((e.State & ScrState.Present) != 0) OnCardFound(sender, e);
        }
```
