### ISSUE TITLE
Detcting when reader is connected

### ISSUE THREAD

**Issue by GAMP** [danm-de/pcsc-sharp#31]
Is it possible to detect when new reader is connected to the system?

**Comment by ctadlock** [comment]
Yes, you need to poll for the connected readers and compare the list to previously connected readers. There isnt a native PCSC event for reader added or removed.

**Comment by GAMP** [comment]
Actually the status function seem to support notifications for new scanner arrivals
https://msdn.microsoft.com/en-us/library/windows/desktop/aa379808(v=vs.85).aspx

"szReader
A pointer to the name of the reader being monitored.
Set the value of this member to "\\\\?PnP?\\Notification" and the values of all other members to zero to be notified of the arrival of a new smart card reader"

Since this library already have most of functions implemented this would be a must.

**Comment by danm-de** [comment]
@GAMP could please provide a working example?

**Comment by olegsavelos** [comment]
Something like this 

```
      public void WaitForScanner()
        {
            using (var cx = _contextFactory.Establish(SCardScope.System))
            {
                var readers = GetReaderNames();

                var scannerStates = new SCARD_READERSTATE[]
                {
                     new SCARD_READERSTATE()
                     {
                         szReader ="\\\\?PnP?\\Notification",
                         pvUserData = IntPtr.Zero,
                         rgbAtr = null,
                         dwCurrentState = (readers.Count() <<16)
                     }

                };

                var rc = SCardGetStatusChange(cx.Handle, 5000, scannerStates, 1);
            }
        }
```
https://msdn.microsoft.com/en-us/library/windows/desktop/aa379773(v=vs.85).aspx

**Comment by olegsavelos** [comment]
This works for arrival and removal, tested with 1 RFID scanner.

```
using (var cx = _contextFactory.Establish(SCardScope.System))
            {
                var readersCount = GetReaderNames().Count();

                var scannerStates = new SCARD_READERSTATE[]
                {
                     new SCARD_READERSTATE()
                     {
                         szReader ="\\\\?PnP?\\Notification",
                         pvUserData = IntPtr.Zero,
                         rgbAtr = null,
                         dwCurrentState = readersCount << 16,
                         dwEventState =  (int)SCRState.Unknown,  
                     }

                };

                var rc = SCardGetStatusChange(cx.Handle, INFINITE, scannerStates, 1);
            }
```

**Comment by danm-de** [comment]
@olegsavelos great! Works for my two OMNIKEY readers as well. 

I was missing the important parts:
```c#
dwCurrentState = readersCount << 16,
dwEventState =  (int)SCRState.Unknown,  
```

**Comment by olegsavelos** [comment]
Yes nothing mentioned on it in MS docs :/ 
Hope you will have it added soon :)

**Comment by danm-de** [comment]
@olegsavelos branch: https://github.com/danm-de/pcsc-sharp/tree/feature/ReaderMonitor
