### ISSUE TITLE
Any plans on netstandard support?

### ISSUE THREAD

**Issue by kant2002** [danm-de/pcsc-sharp#32]
Do you have any plans to support .NET Core via NetStandard support?

**Comment by danm-de** [comment]
Hi,
If I get a pull request that contains the necessary steps (automated build with FAKE, dual packages with "normal" .Net version and additional .NET Core packages,..) I would be happy to merge it :-)

Greetings,
Daniel

**Comment by neman** [comment]
I have used https://github.com/Microsoft/dotnet-apiport for pcsc project, and only know, with netstandard2.0 is 100% portable.

**Comment by chrfin** [comment]
I just submitted a pull request containing a working .NET Standard 2.0 build/package: https://github.com/danm-de/pcsc-sharp/pull/67

**Comment by danm-de** [comment]
New branch for new major release 4.0.0 (.netstandard 2.0)
https://github.com/danm-de/pcsc-sharp/tree/feature/net-standard

**Comment by danm-de** [comment]
Released as version 4.0.0 (master)
