### ISSUE TITLE
Strong Name the Assembly Deployed to NuGet

### ISSUE THREAD

**Issue by ctadlock** [danm-de/pcsc-sharp#33]
other assemblies and applications can't be strong named unless their dependencies are without doing the IL decompiler/recompile hack.

**Comment by danm-de** [comment]
Hi Craig,

Your wish came already up months ago:
https://github.com/danm-de/pcsc-sharp/issues/4

I personally think there is no benefit from using strong names. It is neither a security feature nor makes it your app more "stable". If an attacker was able to replace certain assemblies from your GAC, he/she is able to disable strong-name-verification at all.

Strong names (SNKs) are actually a pain in the a$$ to maintain (think of automated build scripts.., third party dependencies etc.) and it requires some weird "version" hacks to stay semver compatible (bugfix -> version change -> recompile of all dependencies required). There's a minority of commercial users that require strong named assemblies - but those paid developers can easily create a strong named (even X.509 signed) package by themselves.

Do you know how to integrate the signing process in the automated build (FAKE script) 
- supporting both, Windows & Linux
- running out of the box for me (package owner) and others, downloading the sources from GitHub without any manual steps involved?

Greetings,
Daniel

**Comment by ctadlock** [comment]
"I dont like strong naming at all".. not sure how useful of a statement that is. It exists whether any of us like it or not. Every other open source github based project we use has managed to solve this, so it cant be that hard. Look at what JSON.NET does:
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Build/build.ps1

Forcing your developers to branch and maintain a fork is a heavy handed solution for such a small issue that can be solved by just one person (you).

**Comment by danm-de** [comment]
Sorry, will not add strong naming.
