### ISSUE TITLE
Issue reading UID, NFC reader turn off

### ISSUE THREAD

**Issue by itsdb** [danm-de/pcsc-sharp#35]
Hi,
I am using your library pcsc-sharp, version 3.5.1.0 in a Windows 7 environment and have found it to be absolutely perfect for our needs, but every so often (random) we have a issue: when reading of the uid, the NFC reader turns off, and the program stops responding.
To restart the NFC reader you need to disconnect and reconnect the USB connector.
The NFC reader in use is ACS ACR 122U.

What could be the issue?

I attach the file pdf with the C# code used.

Thanks

[NFCReader.pdf](https://github.com/danm-de/pcsc-sharp/files/543812/NFCReader.pdf)

**Comment by danm-de** [comment]
Hi,

pcsc-sharp is a wrapper to the native Windows Smartcard library (winscard.dll). Please check your source code:
- Did you release/dispose the ISCardContext after usage? 
- Did you use an appropriate scope when establishing the context?
- Did you use the correct share mode when connecting to the reader?
- Did you disconnect the reader after usage?
- Did you check your hardware vendor's FAQ / docs / support forum?

Greetings,
Daniel

Note: I did not read your source code - just giving you hints to (hopefully) find problems in your program.

**Comment by itsdb** [comment]
Hi,
- I use the monitor, the context will be automatically released after monitor.Dispose().
- I use context.Establish(SCardScope.System);
- I use SCardShareMode.Shared
- I disconnect the reader: rfidReader.Disconnect(SCardReaderDisposition.Leave);
- We've contacted the hardware vendor's and manufacturer, they reply the problem is software side.

Please, can take a look at the source code? I do not find the error. 

Thank you
