### ISSUE TITLE
"PCSC.PCSCException: Error code: 6" on Remote Desktop reconnect

### ISSUE THREAD

**Issue by SGN-JSE** [danm-de/pcsc-sharp#37]
Hello,

i am trying to use a cardreader on a terminal server over remote desktop.
The cardreader is forwarded through remote desktop and not connected to the target machine directly.

After logging on with remote desktop and starting the program, the card reader is recognized and the SCardMonitor fires the CardInserted and CardRemoved events as expected.

When i disconnect remote desktop, wait a few seconds, and reconnect again, the cardreader is recognized by the program again, but a few moments later my program crashes with an unhandled exception:

PCSC.PCSCException: Error code: 6
   bei PCSC.SCardErrorExtensionMethods.Throw(SCardError sc)
   bei PCSC.SCardContext.Release()
   bei PCSC.SCardContext.Dispose(Boolean disposing)
   bei PCSC.SCardContext.Finalize()

I believe the exception is thrown in the SCardMonitor.
If i do not use SCardMonitor.Start(), the exception is not thrown (but of course i also dont get any card events anymore).

When i disconnect the cardreader by unplugging the usb cable , and plug it in again, everything works fine.

Can you help me with this problem?

**Comment by danm-de** [comment]
Ouch, it's an exception thrown on the finalizer thread (GC), right? I guess you did not explicitly call Dispose() on the SCardContext?

**Comment by SGN-JSE** [comment]
I use "using" statements when i use a SCardContext to get the card readers like this:

                try
                {
                    using (SCardContext Context = new SCardContext())
                    {
                        Context.Establish(SCardScope.User);
                        readerNames = Context.GetReaders();
                    }
                }
                catch (PCSC.PCSCException)
                {
                    logger.Error(string.Format("{0} || {1}", "E10214", ex.Message));
                    return "PCSC.PCSCException";
                }

I keep polling the reader names every second to know when readers get connected/disconnected, and create new SCardMonitors or dispose old SCardMonitors as needed.

When i create a SCardMonitor, i use the new constructor with a ContextFactory:
monitor = new SCardMonitor(contextFactory, SCardScope.User);

The above seems to work fine. Card readers are recognized when i plug them in or unplug them, or when i disconnect or reconnect the remote desktop connection.

After i call
monitor.Start(readerName);
and put a card on the reader, the CardInserted and CardRemoved events fire as expected, and i can continue to unplug/plug card readers without issues.

But if i now disconnect the remote desktop connection, the exception is thrown and crashes the program.

The polling of the Context.GetReaders() throws a few "The Smart card resource manager is not running" errors after disconnecting RDP and before the program crashes. This only happens after disconnecting RDP, not when unplugging the reader.

If i unplug the reader before disconnecting RDP, the program does not crash.

So there seems to be a difference between unplugging a card reader and disconnecting the RDP connection. Perhaps the readers arent porperly unregistered in the system when disconnecting RDP as opposed to unplugging the reader, or something like that? I dont know how PC/SC works in that regard.

I dont know if this is an issue that i should handle somehow, or if this is an issue within SCardMonitor.

Do you have an idea?

**Comment by danm-de** [comment]
Could you please try https://www.nuget.org/packages/PCSC/3.5.3
SCardContext's Dispose method catches ERROR_INVALID_HANDLE exceptions now. The garbage collector calls Dispose in order to free unmanaged resources (last entry from your stacktrace "PCSC.SCardContext.Finalize()").

**Comment by SGN-JSE** [comment]
Yes, the update fixed the issue.
Thank you a lot for your work and the fast update!
