### ISSUE TITLE
CardInsertedEvent reads tag twice

### ISSUE THREAD

**Issue by drajvver** [danm-de/pcsc-sharp#38]
Hello,
I've been using your library with success for over 2 years now. I'm very thankful for it, since it's the only forking lib for C# that I've foun that suits my needs :).
But I have a problem with **CardInsertedEvent**. It reads UID of the card twice, kinda like I would put tag on reader two times in very fast fashion. It's a problem because sometimes it reads valid UID, like _04-70-97-F2-85-2A-80_ but when it reads it "twice" in 75% of cases, the second reading is empty and I don't really know how to manage about it. I need valid UID every time. Is it possible?

```
public string GetCardUid()
        {
            if (!_readerInitialized) ConnectReader();

            var apdu = new CommandApdu(IsoCase.Case2Short, _reader.ActiveProtocol)
            {
                CLA = 0xFF,
                Instruction = InstructionCode.GetData,
                P1 = 0x00,
                P2 = 0x00,
                Le = 0  // We don't know the ID tag size
            };

            try
            {
                var sc = _reader.BeginTransaction();
                if (sc != SCardError.Success)
                {
                    return "";
                }

                var receivePci = new SCardPCI(); // IO returned protocol control information.
                var sendPci = SCardPCI.GetPci(_reader.ActiveProtocol);

                var receiveBuffer = new byte[256];
                var command = apdu.ToArray();

                sc = _reader.Transmit(
                    sendPci, // Protocol Control Information (T0, T1 or Raw)
                    command, // command APDU
                    receivePci, // returning Protocol Control Information
                    ref receiveBuffer); // data buffer

                if (sc != SCardError.Success) return "";

                var responseApdu = new ResponseApdu(receiveBuffer, IsoCase.Case2Short, _reader.ActiveProtocol);

                _reader.EndTransaction(SCardReaderDisposition.Leave);
                _reader.Disconnect(SCardReaderDisposition.Reset);

                _readerInitialized = false;

                var resultUid = "";

                if (responseApdu.HasData)
                {
                    resultUid = BitConverter.ToString(responseApdu.GetData());

                    if(resultUid != _previousUid && !string.IsNullOrWhiteSpace(resultUid))
                        _previousUid = BitConverter.ToString(responseApdu.GetData());
                }

                if (string.IsNullOrWhiteSpace(resultUid))
                    resultUid = _previousUid;

                return resultUid;
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Card Error: {0}", ex.Message);
                return "";
            }
        }
```

**_previousUid** is a private variable

**Comment by JonasChristensen** [comment]
You can use something like this its abit more simple.

	public void getUID() {
		using (var context = new SCardContext()) {
			context.Establish(SCardScope.System);
			
			var readerNames = context.GetReaders();
			if (readerNames == null || readerNames.Length < 1) {
				Console.WriteLine("You need at least one reader in order to run this example.");
				Console.ReadKey();
				return;
			}
						
			using (var isoReader = new IsoReader(context, readerNames[0], SCardShareMode.Shared, SCardProtocol.Any, true)) {
				CommandApdu apdu = new CommandApdu(IsoCase.Case2Short, SCardProtocol.Any) {
					CLA = 0xFF,
					Instruction = InstructionCode.GetData,
					P1 = 0x00,
					P2 = 0x00,
					Le = 0 
				};

				Response response = isoReader.Transmit(apdu);

				if (response.SW2 == 0x00 && response.HasData) {
					Console.WriteLine(BitConverter.ToString(response.GetData()));
				}
				Console.ReadLine();
			}
		}
	}

**Comment by danm-de** [comment]
@drajvver there are several code flaws in your example.

Every time you write..
```
 if (sc != SCardError.Success) return "";
```
..means.:
1. on error -> _"I do not care, just return an empty string"_ (swallow exceptions and return "something" is an anti-pattern)
2. on error -> transaction (if opened) not closed
3. on error -> reader (if successfully opened) not closed

You should have a look at @JonasChristensen provided example. It does not swallow exceptions and disposes allocated resources (using-statement). 

My RFID reader (Omnikey CardMan 5321) emits three events:
1. StatusChanged (New state: Present, InUse) --> DO NOTHING HERE, other process has access to the chip!
2. StatusChanged (New state: Present) --> START HERE
3. StatusChanged (New state: Present, Unpowered) --> after about 10 seconds without usage / chip access
