### ISSUE TITLE
Case3Short APDU in Windows XP

### ISSUE THREAD

**Issue by fschwolow** [danm-de/pcsc-sharp#39]
Using a Case3Short APDU in Windows XP like 

CommandApdu c = new CommandApdu(IsoCase.Case3Short,isoReader.ActiveProtocol) 
{
    CLA = cla,
    INS = ins,
    P1 = p1,
    P2 = p2,
    Data = data
};
Response toReturn = isoReader.Transmit(c);

will throw the following exception:

Unsufficient buffer: check Le size (Le=0)
PCSC.Iso7816.InvalidApduException: Unsufficient buffer: check Le size (Le=0)
---> PCSC.WinErrorInsufficientBufferException: The data area passed to a
system call is too small.
   at PCSC.SCardErrorExtensionMethods.Throw(SCardError sc)
   at PCSC.Iso7816.IsoReader.SimpleTransmit(Byte[] commandApdu, Int32 commandApduLength, IsoCase isoCase, SCardProtocol protocol, SCardPCI receivePci, Byte[] receiveBuffer, Int32 receiveBufferLength)
   at PCSC.Iso7816.IsoReader.Transmit(CommandApdu commandApdu)
   --- End of inner exception stack trace ---
   at PCSC.Iso7816.IsoReader.Transmit(CommandApdu commandApdu)
   at ...

We have to use PCSC with .net 4.0 and Windows XP SP3. This happens under Windows XP only. In Windows 7 everything is fine. Any help would be greatly appreciated!

**Comment by fschwolow** [comment]
The proprosed solution from issue #20 will result in a System.ArgumentException

{"Iso7816-4 Case3Short does not expect any data fields in its return value and therefore has no bytes for Le."}

**Comment by danm-de** [comment]
@fschwolow I do not use Windows XP (for nearly 10 years now). I have no idea how to reproduce and/or test your problem.

Microsoft changed the PC/SC behaviour from time to time (e.g. added new error codes) - so chances are that this is operation system related.

You could download the pcsc-sharp sources, remove all .Net 4.5.1 projects from the solution (pcsc-sharp-rx & examples) and try to debug it.

You could also ditch `IsoReader` and call `ISCardReader.Transmit` directly.

**Comment by danm-de** [comment]
BTW: why Windows XP? Please do not tell me you program for cash machines :-/

**Comment by JonasChristensen** [comment]
Windows XP, sigh.. Its still common in enterprise systems.. Current directory with dll's loading from the wrong directory, printer settings ect.. Alot of issues with XP that 'we' have to maintain/spaghetti code around.

**Comment by DawKaz** [comment]
Hi, 
I've found root cause of this issue
WinXP winscard.dll ver.5.1.2600.5512
Win 7 winscard.dll ver.6.1.7601.17514

class IsoReader.cs, method SimpleTransmit

in XP _receiveBufferLength_  not change, when I changed  _receiveBufferLength_ and _receiveBuffer_, to values which were expected, recived success response

 private ResponseApdu SimpleTransmit(byte[] commandApdu, int commandApduLength, IsoCase isoCase,
            SCardProtocol protocol, SCardPCI receivePci, byte[] receiveBuffer, int receiveBufferLength)
        {
            SCardError sc;
            do {
                // send Command APDU to the card
                **sc = Reader.Transmit(
                    SCardPCI.GetPci(Reader.ActiveProtocol),
                    commandApdu,
                    commandApduLength,
                    receivePci,
                    receiveBuffer,
                    _ref receiveBufferLength_);**

                // Do we need to resend the command APDU?
                if (sc.HasInsufficientBuffer() && receiveBuffer.Length < receiveBufferLength) {
                    // The response buffer was too small.
                    receiveBuffer = new byte[receiveBufferLength];

                    // Shall we wait until we re-send we APDU?
                    if (RetransmitWaitTime > 0) {
                        Thread.Sleep(RetransmitWaitTime);
                    }
                } else {
                    break;
                }
            } while (true);

            if (sc != SCardError.Success) {
                sc.Throw();
            }

            return new ResponseApdu(receiveBuffer, receiveBufferLength, isoCase, protocol);
        }

**Comment by danm-de** [comment]
@DawKaz so, Windows XP does not set ```receiveBufferLength``` correctly?

**Comment by DawKaz** [comment]
Yeah, in win XP reciveBufferLenght is always 2

**Comment by JonasChristensen** [comment]
> BTW: why Windows XP? Please do not tell me that you program for cash machines :-/

Welcome to enterprise systems.. :S

**Comment by fschwolow** [comment]
Thank you! Ditching IsoReader and using ISCardReader.Transmit directly is a work-around for our problem.
