### ISSUE TITLE
Xamarin/Portable .Net support

### ISSUE THREAD

**Issue by WattsC-90** [danm-de/pcsc-sharp#41]
Hi Dan,
I used your library for some testing and was very pleased with how it worked etc., went to create an app for portable (i.e. run on linux and windows), but cannot add it as it says its not compatible with the .net 4.5 portable framework.
How can i get this to work in a project on linux platform aswell as Windows? was really hoping to have a single DLL, given your mention of running on windows and linux!

The nuget error in question: 

> Could not install package 'PCSC 3.6.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Thanks for any help or insight you can give! Iv probably set things up wrong!
Chris

**Comment by danm-de** [comment]
Hi,

you cannot reference a .Net 4.0 assembly (pcsc-sharp.dll) into a .NetPortable. 

When using `mono` (which was the only choice about 10 years ago) you can run/start .Net40 programs / libraries on Linux/MacOS. Change the target of your project from .NETPortable4.5 to .Net Framework 4.5.x (have a look at http://www.mono-project.com/download/ for information about the latest supported framework version).

Greetings,
Daniel

**Comment by WattsC-90** [comment]
Thanks so much, did say i had probably set things up wrong!! Haha.
Can i ask, maybe it should be in another "issue" but not sure.. Have you got an example of the scard monitor cardinserted event? I am unsure what the correct way to use it is! I do not want to use it incorrectly! 
Thanks again

**Comment by danm-de** [comment]
I'd say, run the example and look what kind of events you get. 
* _CardInserted_ + state flag _Present_ (without _InUse_) is a good start, 
* use a new context for reader operations,
* if the class implements `IDisposable` make sure that you free the resources (pcsc-sharp is just a wrapper to the native C++ API). The `using`statement is your friend ;-)
* Microsoft's MSDN articles about the SCARD_* C++ API are very helpful. 

Old fashion `event` example:
https://github.com/danm-de/pcsc-sharp/blob/master/Examples/MonitorReaderEvents/Program.cs
Reaktive Extensions (Rx) example:
https://github.com/danm-de/pcsc-sharp/blob/master/Examples/Reactive/RxEventsTest/Program.cs

If you develop on Windows, you could try the WPF example:
https://github.com/danm-de/pcsc-sharp/tree/master/Examples/Reactive/RxEventsTestWpf

**Comment by WattsC-90** [comment]
Hi Dan,
Thanks for that! The new context was an unexpected twist! I had been using the same context for all elements that needed it.
I shall have a look at the MSDN side of it. Also, I did look at those examples in your codebase, but the issue I had was that the examples show simple printing of strings from within the events, rather than using the reader activated by the event. 
Many thanks for your help!!

**Comment by WattsC-90** [comment]
Hi Dan,
I dont want to open a new ticket because i think all of this is attributed to the "learning/discovery" stage.. so I apologise if you think i should open a new ticket..
I am struggling to get a MiFare classic 1k to read using the example code in your repo. I have copied the code out, but cannot read data. I have put data on using "NFC Tools" app on my phone, but am unable to "ReadBinary". 
background info: using ACR122u reader, 1k classic card, no keys enabled (at least there is no password?) the NFC tools app shows this hex sector on the trailing block (block 0x0b): 

> 00:00:00:00:00:00:7F:07:88:40:00:00:00:00:00:00

I am really quite confused and been trying to crack this for several days now. The datasheet for the reader: http://downloads.acs.com.hk/drivers/en/API-ACR122U-2.02.pdf shows that it has no "Non-Volatile" memory region for loading the keys, which returns false unless I write to VolatileMemory.

Any pointers would be much appreciated, needless to say i am very confused!! Sorry to be such a nuisance!
