### ISSUE TITLE
Adding Signing for pcsc-sharp

### ISSUE THREAD

**Issue by lathan86** [danm-de/pcsc-sharp#43]
Hallo,
Can you include the pull request "Added strong name key"
Have same problem with strong name in signed assembly.
Thanks, 
Lathan

**Comment by MarkusWET** [comment]
Issues #4 and #33 might give you a hint ;)

**Comment by danm-de** [comment]
Hi @lathan86,
as @MarkusWET pointed out, strong named assemblies are not an option for me. I'd say someone should publish a pcsc-sharp-signed version on nuget (as proposed in https://github.com/danm-de/pcsc-sharp/pull/42). 
Sorry :-(
