### ISSUE TITLE
SCardState enum incorrect

### ISSUE THREAD

**Issue by mkeldridge** [danm-de/pcsc-sharp#44]
See: https://msdn.microsoft.com/en-us/library/cc242847.aspx

**Comment by danm-de** [comment]
Hi Mark,
Thanks for the pull request. I will have a deeper look at it later this week. These const values came from the Linux PCSClite project (and worked as expected).
We cannot just change enum values - it would require recompilation of all dependent assemblies. Second, it shall work on Linux as well (which was the target platform of pcsc-sharp).

Greetings,
Daniel

**Comment by mkeldridge** [comment]
Hi Daniel,

This is in the context of using `SCardReader.Status()`. I think this enum was confused with the bitmask enum provided via `SCardGetStatusChange` ([link](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379773(v=vs.85).aspx)) within `SCARD_READERSTATE` ([link](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379808(v=vs.85).aspx)) where it is clearly a bitmask. `SCardStatus` ([link](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379803(v=vs.85).aspx)) doesn't clearly indicate what the enum values are, but it can be inferred from the documentation description and code example that it is not a bitmask. (The switch statement in the code example would use the `HasFlag()` method if it was a bitmask) 

I discovered this issue while debugging `SCardReader.Status()` when it was clear the return values didn't make sense. After searching online I found that the [values from the link in the original comment](https://msdn.microsoft.com/en-us/library/cc242847.aspx) fixed the problem I was seeing.

So either `SCardState` is incorrect or a new enum needs to be made for the return value of `SCardReader.Status()`.

Thanks,
Mark

**Comment by mkeldridge** [comment]
Looks like the difference is pointed out in the documentation for pcsc-lite:
https://pcsclite.alioth.debian.org/api/group__API.html#differences

**Comment by danm-de** [comment]
Hi @mkeldridge,

Thanks for pointing that out! Could you please review https://github.com/danm-de/pcsc-sharp/pull/46?
PCSClite's SCardStatus() seems more powerful, I do not want to cut features for *UNIX users therefore I mapped the Windows enumeration type to the SCardStatus type (enumeration -> bitmask).

Greetings,
Daniel
