### ISSUE TITLE
UAP support

### ISSUE THREAD

**Issue by WattsC-90** [danm-de/pcsc-sharp#47]
Hi Dan, 
loving the library! been using it at every chance I can get, is there any chance of having a UAP (Universal Windows) version available? be great to run it on IOT windows (RPI2 etc).

Cheers!

**Comment by danm-de** [comment]
Hi,
Thanks, nice know. UAP comes with .NET accesable Smardcard & NFC libraries. 

https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/SmartCard/README.md
https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/Nfc/README.md

PCSC-sharp will work on Raspberry PI when using Rasbian Linux + pcscd + mono. 

Greetings,
Daniel

**Comment by WattsC-90** [comment]
Thanks! Will have a look, was trying to use the same library on all platforms. 

On a side note, sorry if this should be a new "issue", does the pcsc library support sending of ioctl commands? I assume, perhaps incorrectly that it is to do with the .Control(..) method?
