### ISSUE TITLE
The Smart card resource manager is not running Windows 10

### ISSUE THREAD

**Issue by mbob001** [danm-de/pcsc-sharp#49]
Hi, after some windows 10 updates, pcsc-sharp stop working. I get an error: 

The Smart card resource manager is not running

I checked service SCardSvr, this service running wihtout error. Service running under Local System.
Where is a problem?
Thanks.

**Comment by AndreasSummer** [comment]
Are you working in an Remote Desktop Session?

**Comment by mbob001** [comment]
Sorry, yes, if I connect by RDP SmartCard not working, If I connect normally, SmartCard working.

**Comment by mbob001** [comment]
I found this: https://superuser.com/questions/543490/access-hosts-smart-card-reader-via-remote-desktop-connection
Exists another way how to do?

**Comment by danm-de** [comment]
Hi @mbob001 

After reading https://blogs.technet.microsoft.com/instan/2011/03/27/why-cant-i-see-my-local-smartcard-readers-when-i-connect-via-rdp/
I found this:

> If Winscard is being loaded in a Terminal Session – all calls to that specific instance of Winscard are redirected to Winscard.dll on the host initiating the RDP connection

Since pcsc-sharp uses P/Invoke calls to `winscard.dll` I do not think you can bypass the _redirection_ feature.

**Comment by danm-de** [comment]
@mbob001 maybe the described hacks from
https://superuser.com/questions/301583/windows-how-to-make-programs-think-theyre-not-running-in-a-terminal-server-ses 
could help?

**Comment by mbob001** [comment]
I am not sure. I try it. One of the solutions is used VNC instead of RDP.

**Comment by AndreasSummer** [comment]
Yes this works or connect the pcsc-device local.

**Comment by mbob001** [comment]
I tried steps from
https://superuser.com/questions/301583/windows-how-to-make-programs-think-theyre-not-running-in-a-terminal-server-ses
but without successful. :(

**Comment by danm-de** [comment]
@mbob001 I guess this behavior is "by design". Keeping in mind that smart cards are often used as login mechanism (e.g. storing login credentials) this makes perfectly sense to me. When using Outlook, you could store your S/MIME pub/priv keys on your smart card - and again it makes sense to forward this device. I do not think I can provide a solution.

**Comment by mbob001** [comment]
Hmm, Thanks for you help.
