### ISSUE TITLE
There is no monitor event for reader connection

### ISSUE THREAD

**Issue by lordofscripts** [danm-de/pcsc-sharp#5]
I have a WinForms application for the smartcard reader (I use the ACR122U reader). If I start the application without the reader connected I get a PCSCException with "No Readers Availabe" which is great, so I handle that.

If there are readers available I list them in a ComboBox. However, If I start the application without readers and then connect it afterwards, the reader itself is operating but the application does not see it because the monitor could not be started.

I think it would be a good addition if the monitor was modified somehow so that it could also start without readers, and then when it detects a reader has been connected, that an event is fired so that the UI application gets notified of the new reader.

**Comment by danm-de** [comment]
Hi,
I like the idea. Do you know of a Windows/Linux API call that notifies me about new connected devices? I did not find any appropriate API function/callback, that sends me back a list of new connected smart card readers. As far as I know there is currently no such method in the Windows Scard API. Active polling using SCardContext.GetReaders(..) within a separated thread would be possible but is ... ugly ;-)

Greetings,
Daniel

**Comment by danm-de** [comment]
On Windows, you could use WMI (Windows Management Instructions) and register for device notifications. Here is an example code (requires import of System.Management):

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Management;

namespace DeviceChangeListener
{
    class Program
    {
        static void Main(string[] args) {
            var watcher = new ManagementEventWatcher();
            var query = new WqlEventQuery("SELECT * FROM Win32_DeviceChangeEvent");
            watcher.EventArrived += OnEventArrived;
            watcher.Query = query;
            watcher.Start();

            Console.ReadKey();
        }

        private static void OnEventArrived(object sender, EventArrivedEventArgs e) {
            Console.WriteLine("Event: {0}", e.NewEvent);
            foreach (var property in e.NewEvent.Properties) {
                Console.WriteLine("{0}: {1}", property.Name, property.Value);
            }
        }
    }
} 
```
I'll close this issue.
