### ISSUE TITLE
Support for CT-API

### ISSUE THREAD

**Issue by kmetic** [danm-de/pcsc-sharp#56]
Hey,

I am using your library for communication with smartcards (PC/SC) and it works great! 

What about the CT-API interface for communication with simple memory cards, for example SLE4442? Is it possible to use pcsc-sharp for this purpose?

Thanks!

**Comment by danm-de** [comment]
Hi @kmetic,

The **C**ard **T**erminal **A**pplication **P**rogramming Interface is a competing API (developed to access health insurance cards in Germany?). Please correct me if I am wrong - Microsoft does not ship any CT-API DLLs, right? As far as I can remember you need a vendor specific driver. If so - there is no single entry point to access ```CT_Init()```, ```CT_Data()``` or ```CT_Close()```. 

Actually I do not even have an idea how to create a wrapper with multivendor-capability for this.

**Comment by kmetic** [comment]
Hey @danm-de,

you are right, I came to the same conclusion - you have to use vendor specific drivers for CT-API. I found one from Omnikey (because I use Omnikey 3021 reader) - [https://www.hidglobal.com/drivers/14877](https://www.hidglobal.com/drivers/14877).

Thanks anyway :)
