### ISSUE TITLE
Remove reference parameters in class SCardReader

### ISSUE THREAD

**Issue by andreapier** [danm-de/pcsc-sharp#58]
Hello,  
Is there any particolar reason for `SCardReader` to use reference parameters (in particolar in `Transmit` method)?  
It makes testing a real pain (I'm using [Moq](https://github.com/Moq/moq4), I don't know if other frameworks are that bad with reference parameters support).  
Do you think we can refactor code to return a response object with `SCardError` and actual response properties?  
Anyway, thanks for your work, it is very helpful!

**Comment by glenebob** [comment]
Unfortunately adding another set of Transmit() overloads that do not use ref will result in quite the clutter.

My project uses a very thin wrapper around the SCardReader class, which returns the number of bytes received. and throws an exception on error. Perhaps that would be an option? Such a wrapper would allow you to mock the reader itself.

**Comment by danm-de** [comment]
Hi Andrea,
Yes you are right. ```ref``` and ```out``` parameters are a pain to test. The interface ```ISCardReader``` and its methods were implemented to behave as _close_ to the original API C-functions as possible.

See Transmit -> https://msdn.microsoft.com/en-us/library/windows/desktop/aa379804(v=vs.85).aspx, 
```c
_Inout_     LPDWORD             pcbRecvLength
```

From the .NET developer's point of view this was obviously a bad design decision. I guess you cannot simply use ```IIsoReader``` instead?

@glenebob suggested a wrapper - it sounds like a very helpful solution at the moment. 

You could use FakeItEasy to mock the interface (http://fakeiteasy.readthedocs.io/en/stable/assigning-out-and-ref-parameters/) - it's still pain though :-(

Let's assume we could start over and redesign the reader interface. Would this be an adequate interface? (Or is it too verbose; already cluttered; any other issues?)

```c#
    public interface IContext
    {
        IReader Connect(string readerName, SCardShareMode mode, SCardProtocol preferredProtocol);
        
        // .. other stuff
    }

    public interface IReader : IDisposable
    {
        string ReaderName { get; }
        ISCardContext CurrentContext { get; }
        SCardShareMode CurrentShareMode { get; }
        SCardProtocol ActiveProtocol { get; }
        IntPtr CardHandle { get; }
        bool IsConnected { get; }

        void Disconnect(SCardReaderDisposition disconnectExecution);
        void Reconnect(SCardShareMode mode, SCardProtocol preferredProtocol, SCardReaderDisposition initialExecution);
        int Transmit(IntPtr sendPci, byte[] sendBuffer, int sendBufferLength, SCardPCI receivePci, byte[] receiveBuffer);
        int Transmit(byte[] sendBuffer, int sendBufferLength, byte[] receiveBuffer);
        int Transmit(byte[] sendBuffer, byte[] receiveBuffer);
        byte[] Transmit(IntPtr sendPci, byte[] sendBuffer, SCardPCI receivePci);
        byte[] Transmit(IntPtr sendPci, byte[] sendBuffer);
        byte[] Transmit(SCardPCI sendPci, byte[] sendBuffer, SCardPCI receivePci);
        byte[] Transmit(byte[] sendBuffer);
        byte[] Control(IntPtr controlCode, byte[] sendBuffer);
        int GetAttrib(IntPtr attributeId, byte[] attribute);
        int GetAttrib(SCardAttribute attributeId, byte[] attribute);
        byte[] GetAttrib(IntPtr attributeId);
        byte[] GetAttrib(SCardAttribute attributeId);
        void SetAttrib(IntPtr attributeId, byte[] attribute, int attributeBufferLength);
        void SetAttrib(IntPtr attributeId, byte[] attribute);
        void SetAttrib(SCardAttribute attributeId, byte[] attribute, int attributeBufferLength);
        void SetAttrib(SCardAttribute attributeId, byte[] attribute);
        IDisposable BeginTransaction();
        IStatus GetStatus();
    }
    
    public interface IStatus
    {
        string[] GetReaderNames();
        SCardState State { get; }
        SCardProtocol Protocol { get; }
        byte[] GetAtr();
    }
```

**Comment by glenebob** [comment]
@danm-de that interface looks good to me, with one issue. It should include overloads of this nature:
int Transmit(byte[] sendBuffer, int sendBufferLength, byte[] receiveBuffer, **int receiveBufferLength**);

**Comment by andreapier** [comment]
@danm-de `IReader` interface looks good to me, and its use is probably straightforward for most .Net developers, so +1 from me!  
@glenebob Your wrapper suggestion is quite a good idea, and it's what I'm using at the moment ;). I just thought that having it integrated into the library would make sense.  Anyway, thanks for the tip, I appreciate it.

**Comment by danm-de** [comment]
Okay. These changes would require a new major release (4.x.x).

**Comment by trivalik** [comment]
@glenebob: adding ´´´int receiveBufferLength"´´´ to call is a duplicate information ´´´receiveBuffer.Length´´´, has this information already

**Comment by danm-de** [comment]
New branch for major release 4.0.0 (.netstandard 2.0)
https://github.com/danm-de/pcsc-sharp/tree/feature/net-standard

Pull requests are welcome :-)

**Comment by danm-de** [comment]
New reader type in version 4.0.0. Please have a look at 
- ```ISCardContext.ConnectReader(..)```
- ```ICardReader```
