### ISSUE TITLE
pcsc-sharp works on NXP proximity but not Broadcom proximity

### ISSUE THREAD

**Issue by fuj1w4r4** [danm-de/pcsc-sharp#60]
I have a Dell Venue 8 Pro 5855 tablet and I  wrote a simple NFC reader by integrated with this library, it works fine and perfect.

Recently, I bought a Dell Latitude 5285 tablet, but this tablet NFC reader manufacturer is Broadcom instead of NXP. Whereby, this library is not able to find this NFC Proximity device.

Is it because of different manufacturer different protocol or anything else?

Device spec:
-Dell latitude 5285
-Windows 10 64-bit
-built-in NFC Proximity Device (Manufacturer: Broadcom)

Please help.

**Comment by danm-de** [comment]
Hi, 
Please ask your PC vendor for a Windows PCSC compliant driver. The c# library does not contain any Windows drivers.

Regards
Daniel
