### ISSUE TITLE
RPI3 and Windows 10 IoT Core

### ISSUE THREAD

**Issue by AlesC89** [danm-de/pcsc-sharp#61]
Hi,

is there a way to run you library on Raspberry PI (2 or 3) and Windows 10 IoT Core with C#?

I managed to make it work on PC, but not on Raspberry PI.

**Comment by fabioravila** [comment]
I've been looking for such functionality for some time.

**Comment by CoyoteProd** [comment]
me too !

**Comment by danielmue** [comment]
Some months ago I was not able to get a *stable* and *sustained* Windows 10 IoT Core installation running. The installation process took hours. Every night (during automatic Windows Updates) Windows destroyed itself. It remained unbootable after automatic reboot. These issues there reproducible with different SD cards.

After three days of disappointing experiences I stopped all my personal investigations. If you get it running, it would ask you to provide a PULL REQUEST containing the nessesary changes.

You will get it working using Raspbian + Mono + pcsclite (daemon).
