### ISSUE TITLE
Memory leak on Windows 10 and Windows Server 2012

### ISSUE THREAD

**Issue by fmtec-software** [danm-de/pcsc-sharp#66]
Hello!
I found your library indicated in some stackoverflow answers and wanted to give it a try to see if the same problem as described here [https://stackoverflow.com/questions/48742884/scardestablishcontext-memory-leak](https://stackoverflow.com/questions/48742884/scardestablishcontext-memory-leak) occurs.
I created a C# console application and in an infinite loop called the [list all connected smartcard readers](https://github.com/danm-de/pcsc-sharp#list-all-connected-smartcard-readers) code, with a small delay after each iteration (10ms). Running the application on my Windows 10 Version 1709 Fall Creators Build 16299.248 (x64), the memory gets constantly increased as well as the handles, until I run in an OutOfMemory exception probably (not waited that long). The same happend with our own library (just using the winscard.dll functions), which worked fine until some time ago.
Running the same application on a Windows 2008 does not lead to such behaviour. The memory does not get increased and the handles remain stable.
I thought first that we are doing something wrong and thought to give your library a try.

I think that it must have something to do with an update from Microsoft, but I cannot figure out a workaround to the situation.
Thanks for any inputs!
Regards
Marius

**Comment by danm-de** [comment]
Hi,
I have Windows 1709 (OS Build 16299.248). 

Using this code with Visual Studio + Diagnostic tools does not seem to increase memory usage:
```csharp
using (var ctx = ContextFactory.Instance.Establish(SCardScope.User)) {
  while (true) {
    var readers = ctx.GetReaders();
  }
}
```
![no-memleak](https://user-images.githubusercontent.com/3825484/36646711-ba5dc174-1a7b-11e8-907b-8706ab15db4f.PNG)

**Comment by danm-de** [comment]
Looking at your code I highly recommend you, to subscribe reader events (attached / detached):
https://github.com/danm-de/pcsc-sharp/tree/master/Examples/ListReaderEvents
