### ISSUE TITLE
Unresolved P/Invoke method 'winscard.dll!SCardEstablishContext' from this method

### ISSUE THREAD

**Issue by foaadnami** [danm-de/pcsc-sharp#70]
Trying to use v4 within a UWP desktop application

I understand with v4, pcsc-sharp is now on .net standard 2.0 which UWP [supports](https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/)

Good news is that we are able to Transmit CommandApdu and read public data of a ISO7816 smart card
Bad news is that this seems to work only in debug mode and when run in release mode we get the following error:

{System.TypeLoadException: Unresolved P/Invoke method 'winscard.dll!SCardEstablishContext' from this method. Please look for this method in build warnings for more details. 

Warning		MCG : warning MCG0007: Unresolved P/Invoke method 'winscard.dll!SCardSetAttrib' for method 'System.Int32 PCSC.Interop.Windows.WinSCardAPI.SCardSetAttrib(System.IntPtr, System.Int32, System.Byte[], System.Int32)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.		

How do you read into this ? Am I trying to do the impossible here ? 

I have tried to enable .net native tool chain in debug mode thats how I got these exception details. I also tried to run in both x64 and x86 modes but it isnt working either. It works in debug mode only when .net native toolchain is not checked in the project properties.

According to the error we have to do DllImport to call those methods, but in the code of pcsc-sharp we already have all those Dll import stuff on the methods we are calling so it doesn't make sense why it is still giving us those errors.

**Comment by danm-de** [comment]
I do not think it is possible to use winscard.dll together with UWP apps. It would be somehow against the concept of the Universal Windows Platform to call external libraries, that are only available on PC (but not on XBox, Windows Phone, ..).

Did you have a look at UWP's smart card API? 
https://docs.microsoft.com/en-us/windows/uwp/security/smart-cards
https://docs.microsoft.com/en-us/uwp/api/windows.devices.smartcards.smartcardconnection

**Comment by WinstonSmith77** [comment]
Maybe it can help to introduce a service that works in win32 and communicates thru 
WCF.

**Comment by foaadnami** [comment]
@danm-de  I took a look at this but seem to have missed *TransmitAsync* which looks promising. Will try this soon.
@WinstonSmith77  We did something similar. Console application that serves the data over an internal webserver. UWP gets the data by calling http://localhost . It worked. Thanks :)

**Comment by danm-de** [comment]
Cannot fix.
