### ISSUE TITLE
NoServiceException: The smar card resource manager is not running. After Windows 10 update.

### ISSUE THREAD

**Issue by stvcortix** [danm-de/pcsc-sharp#71]
After updating Windows 10 Pro to version 10.0.17134 (Build 17134), this problem exists. This update was from the "Feature update to Windows 10, version 1803" and the only Microsoft Windows update from today's date found at Control Panel\All Control Panel Items\Programs and Features\Installed Updates is called: Security Update for Microsoft Windows (KB4103721)

How to recreate this error from running this code:
```
IContextFactory _ContextFactory = ContextFactory.Instance;
using (var context = _ContextFactory.Establish(SCardScope.System)){ }
```
Error thrown from the 2nd line above on "Establish(...)"
> NoServiceException was unhandled by user code
> An exception of type 'PCSC.NoServiceException' occurred in pcsc-sharp.dll but was not handled in user code
> Additional information: The Smart card resource manager is not running.

We have updated our code to reference the newest 4.0.0.0 PCSC and PCSC.Iso7816 .dll files

**Comment by danm-de** [comment]
I've just checked what kind of event triggered SCardSvr to start:
```
C:\WINDOWS\system32>sc.exe qtriggerinfo SCardSvr
[SC] QueryServiceConfig2 SUCCESS

SERVICE_NAME: SCardSvr

        START SERVICE
          DEVICE INTERFACE ARRIVAL     : 50dd5230-ba8a-11d1-bf5d-0000f805f530 [INTERFACE CLASS GUID]
        START SERVICE
          DEVICE INTERFACE ARRIVAL     : 121d8161-866d-4a24-ba58-9058940c0d47 [INTERFACE CLASS GUID]
        START SERVICE
          NETWORK EVENT                : bc90d167-9470-4139-a9ba-be0bbbf5b74d [RPC INTERFACE EVENT]
            DATA                       : c6b5235a-e413-481d-9ac8-31681b1faaf5
        START SERVICE
          NETWORK EVENT                : bc90d167-9470-4139-a9ba-be0bbbf5b74d [RPC INTERFACE EVENT]
            DATA                       : D09BDEB5-6171-4A34-BFE2-06FA82652568:0CC82857-1E0E-4633-A673-257BA24EB9AC
```

The first event was my reader:
``DEVICE INTERFACE ARRIVAL     : 50dd5230-ba8a-11d1-bf5d-0000f805f530``

![omnikey-events](https://user-images.githubusercontent.com/3825484/40137377-909657a8-594a-11e8-9bf4-8041d5c27e7e.PNG)

**Comment by danm-de** [comment]
Ok. The evidence points to a Windows (update) problem 🤔. Since pcsc-sharp is a wrapper around the native library I feel this bug report is not quite right here.

**Comment by stvcortix** [comment]
Ok, yes agreed it is likely a windows update problem. Thanks for your help! I will close this issue.
