### ISSUE TITLE
Why does ISCardApi.Control want an IntPtr for the controlCode?

### ISSUE THREAD

**Issue by BtbN** [danm-de/pcsc-sharp#74]
Both the Windows and pcsc-lite side of things define it as DWORD, which is essentially uint32_t.
On the Windows Interop, the imported function actually does marshal it as an int, but the pcsc-lite one and all the other code in the library treats it as IntPtr.
I'd imagine this to cause issues at least on 64bit pcsc-lite using systems.

**Comment by danm-de** [comment]
Hi,

the data type DWORD has a size of 64bit on my Linux machine. Please have a look:

https://salsa.debian.org/rousseau/PCSC/blob/master/src/PCSC/winscard.h: Line 89

```c
	PCSC_API LONG SCardControl(SCARDHANDLE hCard, DWORD dwControlCode,
		LPCVOID pbSendBuffer, DWORD cbSendLength,
		/*@out@*/ LPVOID pbRecvBuffer, DWORD cbRecvLength,
		LPDWORD lpBytesReturned);
```

https://salsa.debian.org/rousseau/PCSC/blob/master/src/PCSC/wintypes.h: Line 90
```c
    typedef unsigned long DWORD;
```

Test program:
```c
#include <stdio.h>
#include <winscard.h>
int main() {
	printf("DWORD size: %ld bits\n", sizeof(DWORD) * 8);
	return 0;
}
```
Compiled & executed:
```shell
# gcc -I /usr/include/PCSC -o pcsctest pcsctest.c 
# ./pcsctest 
DWORD size: 64 bits
# uname -a
Linux torax 4.13.0-45-generic #50-Ubuntu SMP Wed May 30 08:23:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
On Windows ``DWORD`` stays 32bit. Linux switches from 32bit to 64bit. That was the main reason for splitting the P/Invoke stuff into platform specific files. I'm not sure about the MacOSX version - never tested it.

**Comment by BtbN** [comment]
Oh, I completely missed that the first section of that header is for OSX.
Well, that's odd. Seems like an oversight on their end, which they are now stuck with for ABI compatibility reasons.

Thanks for clearing this up!
