### ISSUE TITLE
Error code: 5

### ISSUE THREAD

**Issue by GioviQ** [danm-de/pcsc-sharp#75]
The following code works in a console app

`    using (var context = contextFactory.Establish(SCardScope.User))
                {
                    readerNames = context.GetReaders();
                }
`

but in a windows service running on the same account gives error code 5.
With system account works, but I cannot use that.

I read also https://blogs.msdn.microsoft.com/alejacma/2011/05/19/scardestablishcontext-fails-with-scard_e_no_service-error/

**Comment by danm-de** [comment]
pcsc-sharp is just a wrapper to Windows' PC/SC API. The error comes from Windows.

Sorry :-(
