### ISSUE TITLE
Connecting to a reader without a card attached

### ISSUE THREAD

**Issue by carol-braileanu** [danm-de/pcsc-sharp#80]
I am using a ACS ACR1222L reader, and I have a few APDU using which I can control different functions on the device, such as setting default buzzer behavior or writing text on screen. I use PCSC Sharp and I was able to successfully connect and read data from cards, as well as sending these ADPUs to the reader as long as there is an RFID tag in range. 

However, I seem not to be able to establish a connection without a card in range, because I get the following error:
`PCSC.Exceptions.RemovedCardException: 'The smart card has been removed, so further communication is not possible.'`. 

The failure happens at the following line of code:
`var rfidReader = new IsoReader(context, readerNames[0], SCardShareMode.Shared, SCardProtocol.Any, false);`

The only way I do not get an error is if I use SCardProtocol.Unset and SCardSharedMode.Direct, but in that case I cannot send ADPUs, I get an error: 
`Protocol 'Unset' not supported.'`

Is there a way to connect to the reader and send ADPUs without a card in the proximity?

Thank you!

**Comment by danm-de** [comment]
Hi,
The only way I know to send commands directly to the reader is ICardReader.Control(...). 

Please try to connect using ISCardContext.ConnectReader(...) with SCardShareMode.Direct and SCardProtocol.Any or SCardProtocol.Raw.

**Comment by danm-de** [comment]
Maybe ICardReader.SetAttrib(...) might work to. Depends on reader / vendor specs.

**Comment by danm-de** [comment]
There is a known problem with ACS readers (e.g. ACR122U)
https://github.com/pokusew/nfc-pcsc/issues/13#issuecomment-302482621

**Comment by carol-braileanu** [comment]
Hello,
Thank you for your tip, I will try to use ctacs.dll instead.

**Comment by limentas** [comment]
Hi.
I'm using ACR1281 and Acr122 on windows and I'll just leave here an example of working code, that connecting to reader without card and turning on auto-polling cards.
```
var smartCardContext = new SCardContext();
smartCardContext.Establish(SCardScope.System);
var reader = new SCardReader(smartCardContext);
reader.Connect("ACS ACR1281 2S CL Reader PICC 0", SCardShareMode.Direct, SCardProtocol.Unset);
var resp = new byte[256];
var apdu = new CommandApdu(IsoCase.Case3Short, SCardProtocol.T0)
{
    CLA = 0xE0,
    Instruction = 0x00,
    P1 = 0x00,
    P2 = 0x23,
    Data = new byte[] { 0x8F }
};
reader.Control(new IntPtr(0x3136b0), apdu.ToArray(), ref resp);
           
```
One prerequisite: you have to switch on escape commands in windows registry by following instructions for Acr122 reader: http://downloads.acs.com.hk/drivers/en/API-ACR122U-2.02.pdf
see Appendix A.
