### ISSUE TITLE
Problem with Alcor Micro USB Reader Throws ErrorCode 1117

### ISSUE THREAD

**Issue by WinstonSmith77** [danm-de/pcsc-sharp#81]
var apdu3 = new CommandApdu(IsoCase.Case2Extended, isoReader.ActiveProtocol)
                {
                    CLA = 0x00, // Class
                    Instruction = InstructionCode.ReadBinary,
                    P1 = 0x81, // Parameter 1
                    P2 = 0x00, // Parameter 2
                    Le = 0x00 // Expected length of the returned data
                };
                response = isoReader.Transmit(apdu3);
                var patient = response.GetData();
                PrintResponse(response);

This code is supposed to read PatientData from German EGK Cards. Works well with other readers.
Can anyone help? Thanks in advance

**Comment by danm-de** [comment]
Sorry, cannot help with application / card specific problems.
