### ISSUE TITLE
Question: Integrate MIFARE ENCODER MF-ECD03 to c#

### ISSUE THREAD

**Issue by armory09** [danm-de/pcsc-sharp#82]
Hi, Im trying to integrate this device MIFARE ENCODER MF-ECD03 into our application which is written in c#. I'm not really sure where could i start. I tried this library but it cannot detect the encoder.
Can anyone please point me out to the right direction.

Thank you so much.

**Comment by danm-de** [comment]
Hi,
Please contact the device vendor and ask for a PC/SC driver. 

Maybe they will provide you a proprietary SDK.
