### ISSUE TITLE
PCSC.Exceptions.PCSCException: Error code: 5

### ISSUE THREAD

**Issue by Rajat196** [danm-de/pcsc-sharp#83]
i am  Developing UWP App  and Add smart Card NFC  in a project using pcsc-sharp nuget package 
, getting error "PCSC.Exceptions.PCSCException: Error code: 5"   when i try 
 _contextFactory.Establish(SCardScope.System)
 try
            {
                using (var context = _contextFactory.Establish(SCardScope.System))
                {
                    lContex = context.GetReaders();
                }
            }
            catch (PCSCException ex)
            {
                Debug.WriteLine(ex.Message);
            }

**Comment by Lasper** [comment]
You need to enable Shared User Certificates capability in the app manifest.

**Comment by danm-de** [comment]
Closed. UWP has a native smart card API. For more info, please see https://docs.microsoft.com/en-us/windows/uwp/security/smart-cards
