### ISSUE TITLE
Net Core 3 seems not working with PCSC

### ISSUE THREAD

**Issue by furoraest** [danm-de/pcsc-sharp#84]
Same code(and hardware) which worked with .net core 2.X, now seems not working with .net core 3

Error message:
Unhandled Exception: PCSC.Exceptions.CommunicationErrorException: An internal communications error has been detected.
   at PCSC.Extensions.CardErrorExt.Throw(SCardError sc)
   at PCSC.SCardContext.Establish(SCardScope scope)
   at PCSC.ContextFactory.Establish(SCardScope scope)
   at ApduTest.GET_CHALLENGE.Program.Main() in /home/user/src/dotnet/pcsc-e1/Program.cs:line 13

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.10
 OS Platform: Linux
 RID:         ubuntu.18.10-x64
 Base Path:   /home/user/bin/dotnet/sdk/3.0.100-preview-010184/

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  3.0.100-preview-010184 [/home/user/bin/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [/home/user/bin/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [/home/user/bin/dotnet/shared/Microsoft.NETCore.App]

**Comment by furoraest** [comment]
Confirmed versions,
it works well with latest .net core 2.1 but not since 2.2
.NET Core SDKs installed:
  2.1.503
Using also latest nuget (4.0.1) version

**Comment by furoraest** [comment]
Confirmed versions,
it works well with latest .net core 2.1 but not since 2.2
.NET Core SDKs installed:
  2.1.503
Using also latest nuget (4.0.1) version

**Comment by danm-de** [comment]
Hi @furoraest,
The new version 4.1.1 was working on my Ubuntu 19.x using the latest .Net Core 2.2

**Comment by Ellerbach** [comment]
I get all working with .NET Core 2.2, compiled with the latest .NET Core 3.0.100-preview6-012264.
I've been using dotnet publish -r linux-arm to have it working on a Raspberry Pi.
It's even working into a Docker container. You just need to make sure to launch pcscd into the container.
So you can add that it's confirmed that it's working on .NET core 2.2 on linux-arm platform.

**Comment by danm-de** [comment]
Cool, thanks for testing! Updated https://github.com/danm-de/pcsc-sharp/blob/master/README.md

I will keep this ticket open until .Net Core 3.0 is released.

**Comment by danm-de** [comment]
New release 5.0.0 support .Net Core 2.2, 3.0 and 3.1
