### ISSUE TITLE
OverFlowException in SCardReaderState.get_EventState()

### ISSUE THREAD

**Issue by JssDWt** [danm-de/pcsc-sharp#86]
I'm running the 'MonitorReaderEvents' sample on a MacBook Pro with a SCL3711 attached in a .Net Core 2.1 app. When I get my phone in range, however, I'm getting an OverFlowException:

> This program will monitor all SmartCard readers and display all status changes.
> Start monitoring for reader SCL3711 Reader and NFC Device.
> Press Ctrl-Q to exit or any key to toggle monitor.
> >> Initialized Event for reader: SCL3711 Reader and NFC Device
> ATR: 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
> State: Unaware
> 
> 
> Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
>    at PCSC.SCardReaderState.get_EventState()
>    at PCSC.Monitoring.SCardMonitor.StartMonitor(Monitor monitor)
>    at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by danm-de** [comment]
Ah sh1t, there is a cast from IntPtr to int that throws (because dwEventState is > than int.MaxValue)...

**Comment by danm-de** [comment]
Should be fixed in master (NuGet 4.0.3). Thanks for reporting!
