### ISSUE TITLE
How monitor card events

### ISSUE THREAD

**Issue by ahvahsky2008** [danm-de/pcsc-sharp#89]
I want send apdu commands, because i use ISO7816.  MonitorFactory namespace not founded. How use it in ISO7816?

```
var monitorFactory = MonitorFactory.Instance;
var monitor = monitorFactory.Create(SCardScope.System);

// connect events here..
monitor.StatusChanged += (sender, args) => 
    Console.WriteLine($"New state: {args.NewState}");

monitor.Start("OMNIKEY CardMan 5x21-CL 0");

Console.ReadKey(); // Press any key to exit

monitor.Cancel();
monitor.Dispose();
```

**Comment by danm-de** [comment]
Please have a look at the example directory:

https://github.com/danm-de/pcsc-sharp/tree/master/Examples/MonitorReaderEvents
https://github.com/danm-de/pcsc-sharp/blob/master/Examples/MonitorReaderEvents/Program.cs

```c#
using PCSC.Monitoring;
```
