### ISSUE TITLE
NuGet packages contain unsigned assemblies

### ISSUE THREAD

**Issue by levicki** [danm-de/pcsc-sharp#90]
When creating ActiveX control in C# in order to avoid unsafe warnings the assembly needs to be strongly named and signed.

That means all the assemblies it references also need to be strongly named and signed.

PCSC.dll and PCSC.Iso7816.dll distributed in NuGet packages are not signed and Internet Explorer refuses to load them when initializing the ActiveX control that uses them.

Could you please provide signed assemblies in NuGet packages?

There were already three pull requests (#42, #43, and #88), as well as previously closed issues #4 and #33 for this. However, I urge you to reconsider it despite your dislike for it, because there are use cases (such as COM interop) where strong names and signing is necessary as I explained above.

**Comment by danm-de** [comment]
Thanks, will be fixed in branch https://github.com/danm-de/pcsc-sharp/tree/bugfix/macos-issue-87
