### ISSUE TITLE
InvalidParameter response from Transmit method on Linux/RPi

### ISSUE THREAD

**Issue by WattsC-90** [danm-de/pcsc-sharp#93]
I have got some code which reads the UID from a card using the OmniKey 5021 CL reader on windows, this works successfully and has no problems. 

I am trying to port this over to be used on the Raspberry PI (zero) using Mono, but the same code which works on windows fails to transmit to the card on the Pi. The `Transmit` method returns `InvalidParameter`. But I am not sure why, given the same code/command reads the same card on windows!

I had wondered if there was a byte ordering issue here, but I honestly dont have enough information to determine that, and it seems (at least as a cursory glance), that it is all little endian so I dont think i need to reverse the send buffer ordering.

Code:
```c#
private void _cardMonitor_CardInserted(object sender, CardStatusEventArgs e)
{
	var ctxFac = ContextFactory.Instance;
	using (var ctx = ctxFac.Establish(SCardScope.System))
	{
		var reader = new SCardReader(ctx);
		var pioSendPci = new IntPtr();
		byte[] rcvBuffer = new byte[256];

		if (_readerName == string.Empty)
		{
			Console.WriteLine("Reader name is somehow empty...");
			return;
		}

		var err = reader.Connect(_readerName, SCardShareMode.Shared, SCardProtocol.Any);
		if (err == SCardError.Success)
		{
			var uIdcmd = new byte[] { 0xFF, 0xCA, 0x00, 0x00, 0x00 };
			
			err = reader.Transmit(pioSendPci, uIdcmd, ref rcvBuffer);
			if (err == SCardError.Success)
			{
				var uid = ConvertByteUIDToString(rcvBuffer);
				var atrString = ConvertByteUIDToString(e.Atr);
				Console.WriteLine("Card Inserted, ATR: " + atrString + ", and UID is: " + uid);
			}
			else
			{
				Console.WriteLine("Failed to Read UID, Error: "+ err);
				Console.WriteLine("PIOSendPci Value: "+ pioSendPci);
				Console.WriteLine("Receive Buffer Value: "+ ConvertByteUIDToString(rcvBuffer));
			}
		}
		else
		{
			Console.WriteLine("Reader failed to connect, error: " + Enum.GetName(typeof(SCardError), err));
		}
	}
}
```

Versions:

> `PCSC` (nuget) version 4.2.0
> `Buster` Rasbian
> 1.8.24 of `pcsc-lite`

I really desperately want to find out what is going on. I have installed the driver for the reader, as it was previously not detecting it at all. Now its the inconsistent behaviour between windows/linux which has me scratching my head!

Any help is much appreciated, if you require more debug info, please let me know

**Comment by danm-de** [comment]
Hi,

what happens if you change the line 

```c#
err = reader.Transmit(pioSendPci, uIdcmd, ref rcvBuffer);
```

with

```c#
var pci = SCardPCI.GetPci(reader.ActiveProtocol);
err = reader.Transmit(pci, uIdcmd, ref rcvBuffer);
```

?

I don't know why Windows allows you to supply `IntPtr.Zero` as protocol control information.

**Comment by danm-de** [comment]
If I understand the docs correctly, you need to choose one of:
- SCARD_PCI_T0, 
- SCARD_PCI_T1, or 
- SCARD_PCI_RAW

NULL (IntPtr.Zero) is not an option.

https://docs.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardtransmit

**Comment by WattsC-90** [comment]
Its very odd that it works! I shall try it out and report back, thanks!

**Comment by WattsC-90** [comment]
yep! thats it! brilliant. Not sure why it worked before, but it works on RPi now! I shall test it again on Windows to make sure it works on both!

Thanks

**Comment by WattsC-90** [comment]
just having a think about this, should code be added to the wrapper to prevent null pointers? `if null throw new argumentnullexception()` type code? because this was a very confusing error/message to get from the system "InvalidParameter". It doesn't help narrow down the issue at all

**Comment by danm-de** [comment]
The pcsc-sharp library shall give you "raw" access to the native PC/SC API. 

If you use `ISCardReader`, you will get full access. There are only a few (necessary conversions), e.g. reduce pointer usage, string encoding, enum mapping, memory management etc...

If you prefer a more C#-like (and testable) interface, please consider to use `ICardReader`
https://github.com/danm-de/pcsc-sharp/blob/master/src/PCSC/ICardReader.cs

_It'll throw Exceptions instead of returning error codes. You can create an instance by calling `ISCardContext.ConnectReader(...)`._

I fear adding a `ArgumentNullException` will break a lot of existing code bases.

Unfortunately the most companies do not release their reader abstractions as open source to Github / NuGet. I used to get tons of requests regarding NFC, Mifare and pcsc-sharp. If only one person had published hers/his library as open source project ... ;-)

Umm, actually there is a higher level API I know of: https://github.com/chakphanu/ThaiNationalIDCard

**Comment by WattsC-90** [comment]
Have you got an example using the `ICardReader`? I can only think I have gone the way I have due to an example I found previously! If there is a better way to do it with Exceptions and more usable errors then I definitely want to use that!
