### ISSUE TITLE
Transmit Error Code: 995

### ISSUE THREAD

**Issue by Yoduh** [danm-de/pcsc-sharp#94]
Trying to run Examples/ISO7816-4/ApduTest.GET_CHALLENG/Program.cs
exception occurs on line isoReader.Transmit(apdu);
Exception is thrown which I catch.  Exception message is "Error code: 995"
stack trace
```
at PCSC.Extensions.CardErrorExt.Throw(SCardError sc) 
at PCSC.Iso7816.IsoReader.SimpleTransmit(Byte[] commandApdu, Int32 commandApduLength, IsoCase isoCase, SCardProtocol protocol, SCardPCI receivePci, Byte[] receiveBuffer, Int32 receiveBufferLength)
at PCSC.Iso7816.IsoReader.Transmit(CommandApdu commandApdu)
```

If all I do is swap the APDU command to the same one used to retrieve a UID in Examples/ISO7816-4/Transmit/Program.cs I get a successful response.  Attempts with any other command results in the 995 error.  This seems to be a system error:
https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--500-999-

> ERROR_OPERATION_ABORTED
995 (0x3E3)
The I/O operation has been aborted because of either a thread exit or an application request.

So could be a problem with my system, but doesn't explain why one command work and others do not.  I'm using a ACR1252U reader with a Mifare Ultralight card. Not really sure where to begin trying to solve this.  Any help would be appreciated.

Thanks

**Comment by danm-de** [comment]
Sorry, I cannot help with application / card specific errors. The GET_CHALLENGE example has been tested using Siemens CardOS chip + Omnikey CardMan 5321.

**Comment by danm-de** [comment]
Please check the spec of your reader. The most vendors provide an API documentation with examples and supported commands (especially for NFC).

https://www.acs.com.hk/download-manual/2359/CMP_ACR122L_1.03.pdf
