### ISSUE TITLE
Does our lib work with Sony RC-S380 NFC Reader/Writer

### ISSUE THREAD

**Issue by phongnt57** [danm-de/pcsc-sharp#95]
Product Specifications of my device:

Communication method:
 - Conforms to ISO/IEC 18092 (212 kbps / 424 kbps Passive communication mode)
 - Conforms to ISO/IEC 14443 (Type A / Type B)

Compatible cards / devices*4 |  
- FeliCa Standard
- FeliCa Lite
- FeliCa Lite-S
- FeliCa Link
- NFC Dynamic Tag (FeliCa Plug)
- Smartphones incorporating a Mobile FeliCa IC chip
- ISO/IEC 14443 Type A, MIFARE, Type B
- MIFARE Classic
- MIFARE Ultralight / Ultralight C
- MIFARE DESFire / DESFire EV1
- MIFARE Plus
- SmartMX
- Jewel / Topaz

API  : 
- PC/SC Ver. 2.0, FeliCa library.

I try with example and get the result : " No card reader found". No exception on output is show, any specific step I have to  do to make it work?

**Comment by danm-de** [comment]
Hi,

It seems that the driver of your reader device doesn't provide a PC/SC interface.

However, after googling around for a while I found this:
https://www.sony.co.jp/Products/felica/consumer/download/pcscactivator.html

You probably need to install additional software from SONY to get a PC/SC compliant driver.
