### ISSUE TITLE
Getting the UID from a card

### ISSUE THREAD

**Issue by forki** [danm-de/pcsc-sharp#96]
I tried to use the lib and it detecs my card. But I want to read the UID. My node.js lib on the raspberry pi gives me something like `1e9426cb`

but I get

![image](https://user-images.githubusercontent.com/57396/68856370-9d511880-06e0-11ea-8d3d-c10da51cd64d.png)

**Comment by danm-de** [comment]
@forki the [ATR](https://de.wikipedia.org/wiki/Answer_to_Reset) is not a unique id.

I guess you want to read an RFID ID / tag? If yes, please have a look here: https://github.com/danm-de/pcsc-sharp/blob/master/Examples/ISO7816-4/Transmit/Program.cs

You need to send an APDU [ISO7816-4 Case2Short](https://cardwerk.com/iso-7816-4-annex-a-smart-card-standard/#AnnexA_2), containing:
CLA = 0xFF
Instruction =  0xCA
P1 = 0x00
P2 = 0x00



(*Note: PC/SC-sharp is not ready to use NFC-Library*)

**Comment by forki** [comment]
Nice!
