### ISSUE TITLE
Receiving "wrong instruction class: 0x6E00" when performing a SELECT command on a MultiFlex cad

### ISSUE THREAD

**Issue by gjermund-stensrud** [danm-de/pcsc-sharp#97]
I'm developing code to interface with MultiFlex cards and I have run into a problem.

I'm trying to perform a SELECT command as follows:

var apdu = new CommandApdu(IsoCase.Case4Short, isoReader.ActiveProtocol) {
            CLA = 0xC0,
            Instruction = InstructionCode.SelectFile,
            Data = new byte[] { 0x3F, 0x00 },
            //Le = 0x02 // Setting this gives an error message about GET RESPONSE for T0 protocol
        };

But whatever I do I get a 0x6E00 response.

After a bit of searching I discovered that the Transmit command in IsoReader sends the SelectFile command correctly and gets a successful response with SW1SW2=0x6114. But within the Transmit function it then proceeds to perform a GetResponse command by calling IssueGetResponseCommand(), because it detects that there is more data available. The problem occurs when it calls ConstructGetResponseAdpu() to build the command. And on line 351 of IsoReader.cs the CLA is hard coded to be 0x00. On MultiFlex cards this class needs to be 0xC0 so when this command is executed the response SW1SW2=0x6E00 (Wrong instruction class).

I have found no way of preventing the IssueGetResponseCommand() function to be called or any way to change the CLA to anything else. In this case 0xC0.

Is there any way to get around this problem?

**Comment by danm-de** [comment]
Oh, not yet.
Check https://github.com/danm-de/pcsc-sharp/pull/98

**Comment by danm-de** [comment]
New release 5.0.0

The CLA byte will be copied from the initial command. There is a new method in [IsoReader.cs](https://github.com/danm-de/pcsc-sharp/blob/master/src/PCSC.Iso7816/IsoReader.cs) line 181 

```charp
IsoReader.Transmit(CommandApdu, ConstructGetResponse)
```

By using the ```ConstructGetResponse``` delegate you can create the GET RESPONSE command by yourself.

**Comment by gjermund-stensrud** [comment]
Excellent!

The ConstructGetResponse function solved the issues I was having. Thank you for quick response!
